(gdl-type-source-v1
  (source-digest "6d60f8180e198232f32de96a66684fcbed1f4a0489f99b7ff6cbe100343483cf")
  (profile-digest "f4d9485b42c4c3ab5bff52f628048ab69b65f91c98eae7e36f140872f3fcb3a2")
  (revision gdl-type-source-0a4d36047b4f80ce50db277978e319af49ecab8030d06ea27f5084f7d944014d)
  (source-text "(bad red)\n(seed a)\n(<= (goal ?x) (seed ?x))\n(<= (reachable ?x) (bad ?x))\n")
  (profile-text "a :: item.\nred :: agent.\nseed, goal :: item -> bool.\nbad, reachable :: prop -> bool.\n"))
