(gdl-type-source-v1
  (source-digest "3afe197ad190ecb72da9eda0c7a0d3a9843a582af2067d718dda774e2a00f156")
  (profile-digest "aea5083c18107c33a7b60a4ba36968e24d2c9dfe7847c07a61f73b4e89f94635")
  (revision gdl-type-source-8e6305395a857e3297828e51d0da12ed53834b05e8a6d87f1849d570d6f5f0bf)
  (source-text "(base p)\n(base q)\n(domain p)\n(domain q)\n(<= (missing ?x) (domain ?x) (not (true ?x)))\n")
  (profile-text "true, base :: prop -> bool.\ndomain, missing :: prop -> bool.\np, q, r :: prop.\n"))
