(gdl-type-source-v1
  (source-digest "c983b2005f9f24e0f1232cbdb12ac1a895ff4ead9ed76e3029f96e9bb34fe42b")
  (profile-digest "cff5aae6c61dc71ed12f573c4ad5093a6ab748153ecfdf858edc28981f4f1d37")
  (revision gdl-type-source-8f99d542d0732090e2c04477ca00396b37f61ca3eadceacd77536881b5098291)
  (source-text "(seed blank)\n(seed red)\n(<= (copy ?x) (seed ?x))\n")
  (profile-text "blank :: cell_type.\nred :: agent.\nagent :> cell_type.\nseed, copy :: cell_type -> bool.\n"))
