(rhometta:run-values
  (gslt-rho:process:InsertRowV1
    QueryMetamathInsertRowCoreRefusedRhoCliV1
    (InsertRowV1
      (StateV1
        MetamathPackageV1 NatZeroV1 (NatSuccV1 NatZeroV1)
        (TablesConsV1
          (TableV1
            MetamathRowsTableV1
            (EntriesConsV1
              (EntryV1 NatZeroV1
                (RowConsV1 NatZeroV1 RowNilV1) NatZeroV1)
              EntriesNilV1))
          TablesNilV1))
      MetamathRowsTableV1
      (NatSuccV1 NatZeroV1)
      StateRequireKeyAbsentV1
      (RowConsV1 NatZeroV1 RowNilV1)
      $outcome $after $history)))
