(rhometta:run-values
  (gslt-rho:process:InsertEachMatchingV1
    QueryMetamathInsertEachMatchingCoreRefusedRhoCliV1
    (InsertEachMatchingV1
      (StateV1
        MetamathPackageV1 NatZeroV1
        (NatSuccV1 (NatSuccV1 NatZeroV1))
        (TablesConsV1
          (TableV1 NatZeroV1
            (EntriesConsV1
              (EntryV1 NatZeroV1
                (RowConsV1 NatZeroV1 RowNilV1) NatZeroV1)
              EntriesNilV1))
          (TablesConsV1
            (TableV1
              (NatSuccV1 NatZeroV1)
              (EntriesConsV1
                (EntryV1 (NatSuccV1 NatZeroV1)
                  (RowConsV1 NatZeroV1
                    (RowConsV1 (NatSuccV1 NatZeroV1) RowNilV1))
                  NatZeroV1)
                EntriesNilV1))
            TablesNilV1)))
      MetamathConstantsGoodOccurrenceV1
      NatZeroV1
      (NatSuccV1 NatZeroV1)
      (NatSuccV1 NatZeroV1)
      StateRequireKeyAbsentV1
      (StateRowConsV1 StateInputV1 StateRowNilV1)
      (StateRowConsV1 StateInputV1
        (StateRowConsV1
          (StateLiteralV1 (NatSuccV1 NatZeroV1))
          StateRowNilV1))
      (ValuesConsV1 NatZeroV1 ValuesNilV1)
      $outcome $after $history)))
