#!/usr/bin/env python3
"""Scope migration controls, with optional replay of the exported Lean corpus."""
from __future__ import annotations

import argparse
import ast
import csv
import importlib.util
import json
import os
import re
from pathlib import Path
import subprocess
import sys

ROOT = Path(__file__).resolve().parents[2]
sys.path.insert(0, str(ROOT / "tools"))
import prime_scope_migration as migration


def run(binary, path, ownership, route):
    env = dict(os.environ, CETTA_PRIME_SCOPE_DEFAULT=ownership)
    env.pop("CETTA_PRIME_SCOPE_CENSUS", None)
    env.pop("CETTA_PRIME_RELATIONAL_PLAN_REFERENCE", None)
    if route == "reference":
        env["CETTA_PRIME_RELATIONAL_PLAN_REFERENCE"] = "1"
    argv = [str(binary), "--lang", "prime"]
    if route == "fuel":
        argv += ["--fuel", "1000000"]
    result = subprocess.run(argv + [str(path)], env=env, cwd=ROOT,
                            capture_output=True, text=True, timeout=60)
    if result.returncode:
        raise AssertionError(f"run failed: {path.name}, {route}: {result.stderr}")
    return result.stdout


def main():
    ap = argparse.ArgumentParser(description=__doc__)
    ap.add_argument("--binary", required=True, type=Path)
    ap.add_argument("--reference", type=Path)
    ap.add_argument("--comparator", type=Path)
    ap.add_argument("--workdir", required=True, type=Path)
    args = ap.parse_args()
    binary = args.binary.resolve()
    args.workdir.mkdir(parents=True, exist_ok=True)
    controls = [
        ("capture", "; keep (let $fake 1 $fake) exactly\n!(let $f (lam z (let $y z (g $y))) (Pair ($f 1) $y))\n", "[(Pair (g 1) 1)]\n"),
        ("independent", "!(let $f (lam z (let $y z (g $y))) (Pair ($f 1) ($f 2)))\n", "[(Pair (g 1) (g 2))]\n"),
        ("conflict", "!(collapse (Pair (let $x 1 $x) (let $x 2 $x)))\n", "[()]\n"),
        ("source-outside", "!(let $y 7 (let $y $y $y))\n", "[7]\n"),
        ("clause-refinement", "(= (check $x) (let $x 2 ok))\n!(collapse (check 1))\n!(check 2)\n", "[()]\n[ok]\n"),
        ("sequential-refinement", "!(let $f (lam z (let* (($x z) ($x z)) $x)) (Pair ($f 1) ($f 2)))\n", "[(Pair 1 2)]\n"),
        ("branch-capture", "!(let $x 2 (case 1 (($x yes) ($y no))))\n", "[no]\n"),
        ("nested-crossing", "!(bind! &scope-index (new-space))\n!(add-atom &scope-index (value 1 one))\n!(add-atom &scope-index (value 2 two))\n(= (lookup $tag) (case $tag (((Tag $x) (match &scope-index (value $x $y) $y)) ((Alt $x) (match &scope-index (value $x $y) $y)))))\n!(lookup (Tag 1))\n!(collapse (lookup (Tag 3)))\n", "[()]\n[()]\n[()]\n[one]\n[()]\n"),
        ("retained-bindings", "!(collapse-bind (function (let $r done (return $r))))\n",
         "[((done (Bindings (($r done)) ())))]\n"),
        ("constructed-repeated", "(= (twice $f) (Pair ($f 1) ($f 2)))\n!(collapse (twice (cons-atom lam (z (let $y z (g $y))))))\n!(collapse (twice (union-atom (lam z) ((let $y z (g $y))))))\n!(collapse (let $h lam (twice ($h z (let $y z (g $y))))))\n!((lam h (collapse (twice (h z (let $y z (g $y)))))) lam)\n",
         "[()]\n[()]\n[()]\n[()]\n"),
    ]
    checks = 0
    for name, text, expected in controls:
        source = args.workdir / (name + ".source.metta")
        target = args.workdir / (name + ".translated.metta")
        source.write_text(text)
        plan = migration.native_plan(binary, source)
        translated, edits, _ = migration.translate(text, plan)
        target.write_text(translated)
        assert not text.startswith(";") or translated.startswith(text.splitlines()[0])
        for route in ("default", "reference", "fuel"):
            before = run(binary, source, "mercury-implicit", route)
            after = run(binary, target, "lexical-fresh", route)
            assert before == expected, (name, route, "source", before, expected)
            assert after == expected, (name, route, "translation", after, expected)
            checks += 2
        if edits:
            corrupt = [dict(r) for r in plan]
            next(r for r in corrupt if r["kind"] in ("cross", "new"))["arity"] += 1
            try:
                migration.translate(text, corrupt)
            except ValueError:
                checks += 1
            else:
                raise AssertionError("accepted a plan with a wrong source shape")
    # Shared HE controls keep their own source. Prime variants in the lane
    # table are generated by the same native scope plan as the libraries.
    with (ROOT / "tests/prime/crossdialect/cases.tsv").open() as table:
        for row in csv.DictReader(table, delimiter="\t"):
            if row.get("prime_scope_translation") != "true":
                continue
            assert row["prime_source"], row
            target = ROOT / row["prime_source"]
            header = ("; Generated by tools/prime_scope_migration.py from "
                      + row["source"] + "; do not edit.\n"
                      "(scope:profile lexical-fresh per-call reference)\n\n")
            source = ROOT / row["source"]
            translated, _, _ = migration.translate(
                source.read_text(), migration.native_plan(binary, source))
            assert target.read_text() == header + translated, target
            checks += 1
    # Native realizations admit exact authored presentations. Their lexical
    # spellings must follow this same analysis, not a separately edited rule.
    native_source = (ROOT / "src/prime_native_calculus.c").read_text()
    def equation_table(name):
        match = re.search(r"static const char \*const\s+" + re.escape(name)
                          + r"\[\] = \{(.*?)\n\};", native_source, re.S)
        assert match, name
        entries = re.findall(r'((?:\s*"(?:[^"\\]|\\.)*"\s*)+),', match[1])
        assert entries, name
        return ["".join(ast.literal_eval(token) for token in
                        re.findall(r'"(?:[^"\\]|\\.)*"', entry))
                for entry in entries]
    def syntax_shape(node):
        return node.word, tuple(syntax_shape(child) for child in node.children)
    names = re.findall(r"static const char \*const\s+(\w+)_RULE_M\[\]", native_source)
    assert names, "no native migration presentations checked"
    for name in names:
        sources, targets = equation_table(name + "_RULE_M"), equation_table(name)
        assert len(sources) == len(targets), name
        for index, (source_text, target_text) in enumerate(zip(sources, targets)):
            source = args.workdir / (name + "-" + str(index) + ".source.metta")
            source.write_text(source_text + "\n")
            translated, _, _ = migration.translate(
                source.read_text(), migration.native_plan(binary, source))
            actual = tuple(map(syntax_shape, migration.SpanReader(translated).document()))
            expected = tuple(map(syntax_shape, migration.SpanReader(target_text).document()))
            assert actual == expected, (name, index, translated, target_text)
            checks += 1
    if args.reference:
        if not args.comparator:
            ap.error("--reference requires --comparator")
        spec = importlib.util.spec_from_file_location("scope_reference_comparator", args.comparator)
        comparator = importlib.util.module_from_spec(spec)
        spec.loader.exec_module(comparator)
        rows = json.loads(args.reference.read_text())["rows"]
        assert rows, "empty reference is not a completed check"
        results = []
        for row in rows:
            source = args.workdir / ("reference-" + row["row"] + ".source.metta")
            target = args.workdir / ("reference-" + row["row"] + ".translated.metta")
            source.write_text(row["program"])
            plan = migration.native_plan(binary, source)
            translated, edits, diagnostics = migration.translate(row["program"], plan)
            target.write_text(translated)
            expected = [{"sexp": value} for value in comparator.parse_bag_line(row["bags"]["M"])]
            for route in ("default", "reference", "fuel"):
                output = run(binary, target, "lexical-fresh", route)
                lines = [line for line in output.splitlines() if line.startswith("[")]
                observed = comparator.parse_bag_line(lines[-1]) if lines else []
                verdict, details = comparator.compare_bags(expected, observed)
                result = {"row": row["row"], "route": route, "verdict": verdict,
                          "edits": edits, "diagnostics": diagnostics, "output": output}
                results.append(result)
                assert verdict == "match", (result, details)
                checks += 1
        (args.workdir / "reference-receipt.json").write_text(json.dumps(results, indent=2) + "\n")
        print(f"Scope translation reference: {len(rows)} rows, {len(results)} route replays")
    print(f"Scope migration controls: {checks} checks passed")


if __name__ == "__main__":
    main()
