!(gslt-rho:query:ProofTraceCompileCompressedV1
   QueryMetamathProofTraceCompileCompressedNilV1
   (ProofTraceCompileCompressedV1
     ProofTraceLabelNilV1 ProofTraceLabelNilV1
     ProofTraceCodeNilV1 $trace))

!(gslt-rho:query:ProofTraceCompileCompressedV1
   QueryMetamathProofTraceCompileCompressedPushApplyV1
   (ProofTraceCompileCompressedV1
     (ProofTraceLabelConsV1 input-hx-v1 ProofTraceLabelNilV1)
     (ProofTraceLabelConsV1 input-identity-v1 ProofTraceLabelNilV1)
     (ProofTraceCodeConsV1 65
       (ProofTraceCodeConsV1 66 ProofTraceCodeNilV1))
     $trace))

!(gslt-rho:query:ProofTraceCompileCompressedV1
   QueryMetamathProofTraceCompileCompressedSaveRestoreV1
   (ProofTraceCompileCompressedV1
     (ProofTraceLabelConsV1 input-hx-v1 ProofTraceLabelNilV1)
     (ProofTraceLabelConsV1 input-identity-v1 ProofTraceLabelNilV1)
     (ProofTraceCodeConsV1 65
       (ProofTraceCodeConsV1 90
         (ProofTraceCodeConsV1 67 ProofTraceCodeNilV1)))
     $trace))

!(gslt-rho:query:ProofTraceCompileCompressedV1
   QueryMetamathProofTraceCompileCompressedDuplicateHeaderV1
   (ProofTraceCompileCompressedV1
     (ProofTraceLabelConsV1 input-hx-v1 ProofTraceLabelNilV1)
     (ProofTraceLabelConsV1 input-hx-v1 ProofTraceLabelNilV1)
     (ProofTraceCodeConsV1 65 ProofTraceCodeNilV1)
     $trace))
