!(gslt-rho:query:StateStepV1
   QueryMetamathInsertAllPairsAcceptedV1
   (StateStepV1
     MetamathPackageV1
     (StateV1
       MetamathPackageV1 NatZeroV1 NatZeroV1
       (TablesConsV1
         (TableV1 MetamathPairTableV1 EntriesNilV1)
         TablesNilV1))
     MetamathConstantsGoodOccurrenceV1
     (StateInsertAllPairsV1
       mm-symbol MetamathPairTableV1 StateInsertOrRequireEqualV1)
     $outcome $after $history))
