(gslt-presentation-v1 TptpCnfClauseDataBridgeV1
  (signature
    (operator metta-equation 2)
    (operator node 2)
    (operator pair 2)
    (operator cons 2)
    (operator some 1)
    (operator cp 1)
    (operator let 3)
    (operator collapse 1)
    (operator metta-nullary 1)
    (operator cons-atom 2)
    (operator + 2)
    (operator langdef:codepoints->string 1)

    (operator tptp:text 1)
    (operator tptp:symbol-name 1)
    (operator tptp:numeric-kind 1)
    (operator tptp:formula-name 1)
    (operator tptp:role 1)
    (operator tptp:annotation 1)
    (operator tptp:syntax 1)
    (operator tptp:syntax-label 1)
    (operator tptp:syntax-list-1 1)
    (operator tptp:syntax-list-2 2)
    (operator tptp:syntax-list-3 3)
    (operator tptp:term 2)
    (operator tptp:arguments 2)
    (operator tptp:term-rest 2)
    (operator tptp:predicate 2)
    (operator tptp:literal 2)
    (operator tptp:literal-rest 2)
    (operator tptp:clause 2)
    (operator tptp:cnf 3)
    (operator tptp:inputs 3)
    (operator tptp:ast->problem 2)
    (operator tptp:raw->syntax-tree 1)
    (operator tptp:syntax-tree->raw 1)
    (operator tptp:syntax-tree-label 1)
    (operator tptp:syntax-tree-raw-label 1)
    (operator tptp:parse->syntax-tree 1)
    (operator tptp:prepared-raw 1)
    (operator tptp:prepared-digest 1)
    (operator tptp:syntax-tree->problem 2)
    (operator tptp:parse->clause-data 1)
    (operator tptp-cnf:parse->import 1)
    (operator tptp:empty 1)

    (operator fo-cnf:source-digest 1)
    (operator fo-cnf:occurrence 2)
    (operator fo-cnf:formula-name-atomic 1)
    (operator fo-cnf:formula-name-integer 1)
    (operator fo-cnf:role 2)
    (operator fo-cnf:symbol-name 2)
    (operator fo-cnf:variable-name 1)
    (operator fo-cnf:variable-id 2)
    (operator fo-cnf:term-variable 1)
    (operator fo-cnf:term-function 2)
    (operator fo-cnf:term-number 2)
    (operator fo-cnf:term-distinct 1)
    (operator fo-cnf:terms-cons 2)
    (operator fo-cnf:atom-predicate 2)
    (operator fo-cnf:atom-equality 2)
    (operator fo-cnf:literal-positive 1)
    (operator fo-cnf:literal-negative 1)
    (operator fo-cnf:literals-cons 2)
    (operator fo-cnf:syntax-atom 1)
    (operator fo-cnf:syntax-string 1)
    (operator fo-cnf:syntax-integer 1)
    (operator fo-cnf:syntax-list 1)
    (operator fo-cnf:syntax-nodes-cons 2)
    (operator fo-cnf:annotation-tree 1)
    (operator fo-cnf:clause 6)
    (operator fo-cnf:clauses-cons 2)
    (operator fo-cnf:problem 2)

    (operator tptp-cst:node 2)
    (operator tptp-cst:codepoint 1)
    (operator tptp-cst:pair 2)
    (operator tptp-cst:cons 2)
    (operator tptp-cst:some 1)
    (operator tptp-cst:none 0)
    (operator tptp-cst:nil 0)
    (operator tptp-cst:label-and 0)
    (operator tptp-cst:label-arguments 0)
    (operator tptp-cst:label-application 0)
    (operator tptp-cst:label-atomic 0)
    (operator tptp-cst:label-back-quoted 0)
    (operator tptp-cst:label-iff 0)
    (operator tptp-cst:label-implies 0)
    (operator tptp-cst:label-reverse-implies 0)
    (operator tptp-cst:label-xor 0)
    (operator tptp-cst:label-nor 0)
    (operator tptp-cst:label-nand 0)
    (operator tptp-cst:label-cnf 0)
    (operator tptp-cst:label-cnf-disjunction 0)
    (operator tptp-cst:label-negative-literal 0)
    (operator tptp-cst:label-negative-paren-literal 0)
    (operator tptp-cst:label-positive-literal 0)
    (operator tptp-cst:label-defined-application 0)
    (operator tptp-cst:label-defined-word 0)
    (operator tptp-cst:label-disequality 0)
    (operator tptp-cst:label-distinct-object 0)
    (operator tptp-cst:label-equality 0)
    (operator tptp-cst:label-fof 0)
    (operator tptp-cst:label-formula-role 0)
    (operator tptp-cst:label-constant 0)
    (operator tptp-cst:label-defined-constant 0)
    (operator tptp-cst:label-system-constant 0)
    (operator tptp-cst:label-number 0)
    (operator tptp-cst:label-distinct 0)
    (operator tptp-cst:label-general-empty-list 0)
    (operator tptp-cst:label-general-list 0)
    (operator tptp-cst:label-general-function 0)
    (operator tptp-cst:label-general-atomic 0)
    (operator tptp-cst:label-general-variable 0)
    (operator tptp-cst:label-general-number 0)
    (operator tptp-cst:label-general-distinct 0)
    (operator tptp-cst:label-general-term 0)
    (operator tptp-cst:label-general-terms 0)
    (operator tptp-cst:label-include 0)
    (operator tptp-cst:label-integer 0)
    (operator tptp-cst:label-lower-word 0)
    (operator tptp-cst:label-name-list 0)
    (operator tptp-cst:label-or 0)
    (operator tptp-cst:label-forall 0)
    (operator tptp-cst:label-exists 0)
    (operator tptp-cst:label-rational 0)
    (operator tptp-cst:label-real 0)
    (operator tptp-cst:label-single-quoted 0)
    (operator tptp-cst:label-system-application 0)
    (operator tptp-cst:label-system-word 0)
    (operator tptp-cst:label-variable 0)
    (operator tptp-cst:label-block-comment 0)
    (operator tptp-cst:label-tptp-file 0)
    (operator tptp-cst:label-line-comment 0)
    (operator tptp-cst:label-negation 0)
    (operator tptp-cst:label-paren 0)
    (operator tptp-cst:label-upper-word 0)
    (operator tptp-cst:label-variable-list 0)

    (operator LangDef:ImportPrepared 4)
    (operator LangDef:ImportReady 2))
  (equations)
  (rewrites
    (rule eq-empty
      (head
        (metta-equation
          (tptp:empty empty)
          (collapse (metta-nullary empty))))
      (body))
    (rule eq-syntax-tree-label-and
      (head
        (metta-equation
          (tptp:syntax-tree-label and)
          (tptp-cst:label-and)))
      (body))
    (rule eq-syntax-tree-raw-label-and
      (head
        (metta-equation
          (tptp:syntax-tree-raw-label (tptp-cst:label-and))
          and))
      (body))

    (rule eq-syntax-tree-label-arguments
      (head
        (metta-equation
          (tptp:syntax-tree-label arguments)
          (tptp-cst:label-arguments)))
      (body))
    (rule eq-syntax-tree-raw-label-arguments
      (head
        (metta-equation
          (tptp:syntax-tree-raw-label (tptp-cst:label-arguments))
          arguments))
      (body))

    (rule eq-syntax-tree-label-application
      (head
        (metta-equation
          (tptp:syntax-tree-label application)
          (tptp-cst:label-application)))
      (body))
    (rule eq-syntax-tree-raw-label-application
      (head
        (metta-equation
          (tptp:syntax-tree-raw-label (tptp-cst:label-application))
          application))
      (body))

    (rule eq-syntax-tree-label-atomic
      (head
        (metta-equation
          (tptp:syntax-tree-label atomic)
          (tptp-cst:label-atomic)))
      (body))
    (rule eq-syntax-tree-raw-label-atomic
      (head
        (metta-equation
          (tptp:syntax-tree-raw-label (tptp-cst:label-atomic))
          atomic))
      (body))

    (rule eq-syntax-tree-label-back-quoted
      (head
        (metta-equation
          (tptp:syntax-tree-label back-quoted)
          (tptp-cst:label-back-quoted)))
      (body))
    (rule eq-syntax-tree-raw-label-back-quoted
      (head
        (metta-equation
          (tptp:syntax-tree-raw-label (tptp-cst:label-back-quoted))
          back-quoted))
      (body))

    (rule eq-syntax-tree-label-iff
      (head
        (metta-equation
          (tptp:syntax-tree-label iff)
          (tptp-cst:label-iff)))
      (body))
    (rule eq-syntax-tree-raw-label-iff
      (head
        (metta-equation
          (tptp:syntax-tree-raw-label (tptp-cst:label-iff))
          iff))
      (body))

    (rule eq-syntax-tree-label-implies
      (head
        (metta-equation
          (tptp:syntax-tree-label implies)
          (tptp-cst:label-implies)))
      (body))
    (rule eq-syntax-tree-raw-label-implies
      (head
        (metta-equation
          (tptp:syntax-tree-raw-label (tptp-cst:label-implies))
          implies))
      (body))

    (rule eq-syntax-tree-label-reverse-implies
      (head
        (metta-equation
          (tptp:syntax-tree-label reverse-implies)
          (tptp-cst:label-reverse-implies)))
      (body))
    (rule eq-syntax-tree-raw-label-reverse-implies
      (head
        (metta-equation
          (tptp:syntax-tree-raw-label (tptp-cst:label-reverse-implies))
          reverse-implies))
      (body))

    (rule eq-syntax-tree-label-xor
      (head
        (metta-equation
          (tptp:syntax-tree-label xor)
          (tptp-cst:label-xor)))
      (body))
    (rule eq-syntax-tree-raw-label-xor
      (head
        (metta-equation
          (tptp:syntax-tree-raw-label (tptp-cst:label-xor))
          xor))
      (body))

    (rule eq-syntax-tree-label-nor
      (head
        (metta-equation
          (tptp:syntax-tree-label nor)
          (tptp-cst:label-nor)))
      (body))
    (rule eq-syntax-tree-raw-label-nor
      (head
        (metta-equation
          (tptp:syntax-tree-raw-label (tptp-cst:label-nor))
          nor))
      (body))

    (rule eq-syntax-tree-label-nand
      (head
        (metta-equation
          (tptp:syntax-tree-label nand)
          (tptp-cst:label-nand)))
      (body))
    (rule eq-syntax-tree-raw-label-nand
      (head
        (metta-equation
          (tptp:syntax-tree-raw-label (tptp-cst:label-nand))
          nand))
      (body))

    (rule eq-syntax-tree-label-cnf
      (head
        (metta-equation
          (tptp:syntax-tree-label cnf)
          (tptp-cst:label-cnf)))
      (body))
    (rule eq-syntax-tree-raw-label-cnf
      (head
        (metta-equation
          (tptp:syntax-tree-raw-label (tptp-cst:label-cnf))
          cnf))
      (body))

    (rule eq-syntax-tree-label-cnf-disjunction
      (head
        (metta-equation
          (tptp:syntax-tree-label cnf-disjunction)
          (tptp-cst:label-cnf-disjunction)))
      (body))
    (rule eq-syntax-tree-raw-label-cnf-disjunction
      (head
        (metta-equation
          (tptp:syntax-tree-raw-label (tptp-cst:label-cnf-disjunction))
          cnf-disjunction))
      (body))

    (rule eq-syntax-tree-label-negative-literal
      (head
        (metta-equation
          (tptp:syntax-tree-label negative-literal)
          (tptp-cst:label-negative-literal)))
      (body))
    (rule eq-syntax-tree-raw-label-negative-literal
      (head
        (metta-equation
          (tptp:syntax-tree-raw-label (tptp-cst:label-negative-literal))
          negative-literal))
      (body))

    (rule eq-syntax-tree-label-negative-paren-literal
      (head
        (metta-equation
          (tptp:syntax-tree-label negative-paren-literal)
          (tptp-cst:label-negative-paren-literal)))
      (body))
    (rule eq-syntax-tree-raw-label-negative-paren-literal
      (head
        (metta-equation
          (tptp:syntax-tree-raw-label (tptp-cst:label-negative-paren-literal))
          negative-paren-literal))
      (body))

    (rule eq-syntax-tree-label-positive-literal
      (head
        (metta-equation
          (tptp:syntax-tree-label positive-literal)
          (tptp-cst:label-positive-literal)))
      (body))
    (rule eq-syntax-tree-raw-label-positive-literal
      (head
        (metta-equation
          (tptp:syntax-tree-raw-label (tptp-cst:label-positive-literal))
          positive-literal))
      (body))

    (rule eq-syntax-tree-label-defined-application
      (head
        (metta-equation
          (tptp:syntax-tree-label defined-application)
          (tptp-cst:label-defined-application)))
      (body))
    (rule eq-syntax-tree-raw-label-defined-application
      (head
        (metta-equation
          (tptp:syntax-tree-raw-label (tptp-cst:label-defined-application))
          defined-application))
      (body))

    (rule eq-syntax-tree-label-defined-word
      (head
        (metta-equation
          (tptp:syntax-tree-label defined-word)
          (tptp-cst:label-defined-word)))
      (body))
    (rule eq-syntax-tree-raw-label-defined-word
      (head
        (metta-equation
          (tptp:syntax-tree-raw-label (tptp-cst:label-defined-word))
          defined-word))
      (body))

    (rule eq-syntax-tree-label-disequality
      (head
        (metta-equation
          (tptp:syntax-tree-label disequality)
          (tptp-cst:label-disequality)))
      (body))
    (rule eq-syntax-tree-raw-label-disequality
      (head
        (metta-equation
          (tptp:syntax-tree-raw-label (tptp-cst:label-disequality))
          disequality))
      (body))

    (rule eq-syntax-tree-label-distinct-object
      (head
        (metta-equation
          (tptp:syntax-tree-label distinct-object)
          (tptp-cst:label-distinct-object)))
      (body))
    (rule eq-syntax-tree-raw-label-distinct-object
      (head
        (metta-equation
          (tptp:syntax-tree-raw-label (tptp-cst:label-distinct-object))
          distinct-object))
      (body))

    (rule eq-syntax-tree-label-equality
      (head
        (metta-equation
          (tptp:syntax-tree-label equality)
          (tptp-cst:label-equality)))
      (body))
    (rule eq-syntax-tree-raw-label-equality
      (head
        (metta-equation
          (tptp:syntax-tree-raw-label (tptp-cst:label-equality))
          equality))
      (body))

    (rule eq-syntax-tree-label-fof
      (head
        (metta-equation
          (tptp:syntax-tree-label fof)
          (tptp-cst:label-fof)))
      (body))
    (rule eq-syntax-tree-raw-label-fof
      (head
        (metta-equation
          (tptp:syntax-tree-raw-label (tptp-cst:label-fof))
          fof))
      (body))

    (rule eq-syntax-tree-label-formula-role
      (head
        (metta-equation
          (tptp:syntax-tree-label formula-role)
          (tptp-cst:label-formula-role)))
      (body))
    (rule eq-syntax-tree-raw-label-formula-role
      (head
        (metta-equation
          (tptp:syntax-tree-raw-label (tptp-cst:label-formula-role))
          formula-role))
      (body))

    (rule eq-syntax-tree-label-constant
      (head
        (metta-equation
          (tptp:syntax-tree-label constant)
          (tptp-cst:label-constant)))
      (body))
    (rule eq-syntax-tree-raw-label-constant
      (head
        (metta-equation
          (tptp:syntax-tree-raw-label (tptp-cst:label-constant))
          constant))
      (body))

    (rule eq-syntax-tree-label-defined-constant
      (head
        (metta-equation
          (tptp:syntax-tree-label defined-constant)
          (tptp-cst:label-defined-constant)))
      (body))
    (rule eq-syntax-tree-raw-label-defined-constant
      (head
        (metta-equation
          (tptp:syntax-tree-raw-label (tptp-cst:label-defined-constant))
          defined-constant))
      (body))

    (rule eq-syntax-tree-label-system-constant
      (head
        (metta-equation
          (tptp:syntax-tree-label system-constant)
          (tptp-cst:label-system-constant)))
      (body))
    (rule eq-syntax-tree-raw-label-system-constant
      (head
        (metta-equation
          (tptp:syntax-tree-raw-label (tptp-cst:label-system-constant))
          system-constant))
      (body))

    (rule eq-syntax-tree-label-number
      (head
        (metta-equation
          (tptp:syntax-tree-label number)
          (tptp-cst:label-number)))
      (body))
    (rule eq-syntax-tree-raw-label-number
      (head
        (metta-equation
          (tptp:syntax-tree-raw-label (tptp-cst:label-number))
          number))
      (body))

    (rule eq-syntax-tree-label-distinct
      (head
        (metta-equation
          (tptp:syntax-tree-label distinct)
          (tptp-cst:label-distinct)))
      (body))
    (rule eq-syntax-tree-raw-label-distinct
      (head
        (metta-equation
          (tptp:syntax-tree-raw-label (tptp-cst:label-distinct))
          distinct))
      (body))

    (rule eq-syntax-tree-label-general-empty-list
      (head
        (metta-equation
          (tptp:syntax-tree-label general-empty-list)
          (tptp-cst:label-general-empty-list)))
      (body))
    (rule eq-syntax-tree-raw-label-general-empty-list
      (head
        (metta-equation
          (tptp:syntax-tree-raw-label (tptp-cst:label-general-empty-list))
          general-empty-list))
      (body))

    (rule eq-syntax-tree-label-general-list
      (head
        (metta-equation
          (tptp:syntax-tree-label general-list)
          (tptp-cst:label-general-list)))
      (body))
    (rule eq-syntax-tree-raw-label-general-list
      (head
        (metta-equation
          (tptp:syntax-tree-raw-label (tptp-cst:label-general-list))
          general-list))
      (body))

    (rule eq-syntax-tree-label-general-function
      (head
        (metta-equation
          (tptp:syntax-tree-label general-function)
          (tptp-cst:label-general-function)))
      (body))
    (rule eq-syntax-tree-raw-label-general-function
      (head
        (metta-equation
          (tptp:syntax-tree-raw-label (tptp-cst:label-general-function))
          general-function))
      (body))

    (rule eq-syntax-tree-label-general-atomic
      (head
        (metta-equation
          (tptp:syntax-tree-label general-atomic)
          (tptp-cst:label-general-atomic)))
      (body))
    (rule eq-syntax-tree-raw-label-general-atomic
      (head
        (metta-equation
          (tptp:syntax-tree-raw-label (tptp-cst:label-general-atomic))
          general-atomic))
      (body))

    (rule eq-syntax-tree-label-general-variable
      (head
        (metta-equation
          (tptp:syntax-tree-label general-variable)
          (tptp-cst:label-general-variable)))
      (body))
    (rule eq-syntax-tree-raw-label-general-variable
      (head
        (metta-equation
          (tptp:syntax-tree-raw-label (tptp-cst:label-general-variable))
          general-variable))
      (body))

    (rule eq-syntax-tree-label-general-number
      (head
        (metta-equation
          (tptp:syntax-tree-label general-number)
          (tptp-cst:label-general-number)))
      (body))
    (rule eq-syntax-tree-raw-label-general-number
      (head
        (metta-equation
          (tptp:syntax-tree-raw-label (tptp-cst:label-general-number))
          general-number))
      (body))

    (rule eq-syntax-tree-label-general-distinct
      (head
        (metta-equation
          (tptp:syntax-tree-label general-distinct)
          (tptp-cst:label-general-distinct)))
      (body))
    (rule eq-syntax-tree-raw-label-general-distinct
      (head
        (metta-equation
          (tptp:syntax-tree-raw-label (tptp-cst:label-general-distinct))
          general-distinct))
      (body))

    (rule eq-syntax-tree-label-general-term
      (head
        (metta-equation
          (tptp:syntax-tree-label general-term)
          (tptp-cst:label-general-term)))
      (body))
    (rule eq-syntax-tree-raw-label-general-term
      (head
        (metta-equation
          (tptp:syntax-tree-raw-label (tptp-cst:label-general-term))
          general-term))
      (body))

    (rule eq-syntax-tree-label-general-terms
      (head
        (metta-equation
          (tptp:syntax-tree-label general-terms)
          (tptp-cst:label-general-terms)))
      (body))
    (rule eq-syntax-tree-raw-label-general-terms
      (head
        (metta-equation
          (tptp:syntax-tree-raw-label (tptp-cst:label-general-terms))
          general-terms))
      (body))

    (rule eq-syntax-tree-label-include
      (head
        (metta-equation
          (tptp:syntax-tree-label include)
          (tptp-cst:label-include)))
      (body))
    (rule eq-syntax-tree-raw-label-include
      (head
        (metta-equation
          (tptp:syntax-tree-raw-label (tptp-cst:label-include))
          include))
      (body))

    (rule eq-syntax-tree-label-integer
      (head
        (metta-equation
          (tptp:syntax-tree-label integer)
          (tptp-cst:label-integer)))
      (body))
    (rule eq-syntax-tree-raw-label-integer
      (head
        (metta-equation
          (tptp:syntax-tree-raw-label (tptp-cst:label-integer))
          integer))
      (body))

    (rule eq-syntax-tree-label-lower-word
      (head
        (metta-equation
          (tptp:syntax-tree-label lower-word)
          (tptp-cst:label-lower-word)))
      (body))
    (rule eq-syntax-tree-raw-label-lower-word
      (head
        (metta-equation
          (tptp:syntax-tree-raw-label (tptp-cst:label-lower-word))
          lower-word))
      (body))

    (rule eq-syntax-tree-label-name-list
      (head
        (metta-equation
          (tptp:syntax-tree-label name-list)
          (tptp-cst:label-name-list)))
      (body))
    (rule eq-syntax-tree-raw-label-name-list
      (head
        (metta-equation
          (tptp:syntax-tree-raw-label (tptp-cst:label-name-list))
          name-list))
      (body))

    (rule eq-syntax-tree-label-or
      (head
        (metta-equation
          (tptp:syntax-tree-label or)
          (tptp-cst:label-or)))
      (body))
    (rule eq-syntax-tree-raw-label-or
      (head
        (metta-equation
          (tptp:syntax-tree-raw-label (tptp-cst:label-or))
          or))
      (body))

    (rule eq-syntax-tree-label-forall
      (head
        (metta-equation
          (tptp:syntax-tree-label forall)
          (tptp-cst:label-forall)))
      (body))
    (rule eq-syntax-tree-raw-label-forall
      (head
        (metta-equation
          (tptp:syntax-tree-raw-label (tptp-cst:label-forall))
          forall))
      (body))

    (rule eq-syntax-tree-label-exists
      (head
        (metta-equation
          (tptp:syntax-tree-label exists)
          (tptp-cst:label-exists)))
      (body))
    (rule eq-syntax-tree-raw-label-exists
      (head
        (metta-equation
          (tptp:syntax-tree-raw-label (tptp-cst:label-exists))
          exists))
      (body))

    (rule eq-syntax-tree-label-rational
      (head
        (metta-equation
          (tptp:syntax-tree-label rational)
          (tptp-cst:label-rational)))
      (body))
    (rule eq-syntax-tree-raw-label-rational
      (head
        (metta-equation
          (tptp:syntax-tree-raw-label (tptp-cst:label-rational))
          rational))
      (body))

    (rule eq-syntax-tree-label-real
      (head
        (metta-equation
          (tptp:syntax-tree-label real)
          (tptp-cst:label-real)))
      (body))
    (rule eq-syntax-tree-raw-label-real
      (head
        (metta-equation
          (tptp:syntax-tree-raw-label (tptp-cst:label-real))
          real))
      (body))

    (rule eq-syntax-tree-label-single-quoted
      (head
        (metta-equation
          (tptp:syntax-tree-label single-quoted)
          (tptp-cst:label-single-quoted)))
      (body))
    (rule eq-syntax-tree-raw-label-single-quoted
      (head
        (metta-equation
          (tptp:syntax-tree-raw-label (tptp-cst:label-single-quoted))
          single-quoted))
      (body))

    (rule eq-syntax-tree-label-system-application
      (head
        (metta-equation
          (tptp:syntax-tree-label system-application)
          (tptp-cst:label-system-application)))
      (body))
    (rule eq-syntax-tree-raw-label-system-application
      (head
        (metta-equation
          (tptp:syntax-tree-raw-label (tptp-cst:label-system-application))
          system-application))
      (body))

    (rule eq-syntax-tree-label-system-word
      (head
        (metta-equation
          (tptp:syntax-tree-label system-word)
          (tptp-cst:label-system-word)))
      (body))
    (rule eq-syntax-tree-raw-label-system-word
      (head
        (metta-equation
          (tptp:syntax-tree-raw-label (tptp-cst:label-system-word))
          system-word))
      (body))

    (rule eq-syntax-tree-label-variable
      (head
        (metta-equation
          (tptp:syntax-tree-label variable)
          (tptp-cst:label-variable)))
      (body))
    (rule eq-syntax-tree-raw-label-variable
      (head
        (metta-equation
          (tptp:syntax-tree-raw-label (tptp-cst:label-variable))
          variable))
      (body))

    (rule eq-syntax-tree-label-block-comment
      (head
        (metta-equation
          (tptp:syntax-tree-label block-comment)
          (tptp-cst:label-block-comment)))
      (body))
    (rule eq-syntax-tree-raw-label-block-comment
      (head
        (metta-equation
          (tptp:syntax-tree-raw-label (tptp-cst:label-block-comment))
          block-comment))
      (body))

    (rule eq-syntax-tree-label-tptp-file
      (head
        (metta-equation
          (tptp:syntax-tree-label tptp-file)
          (tptp-cst:label-tptp-file)))
      (body))
    (rule eq-syntax-tree-raw-label-tptp-file
      (head
        (metta-equation
          (tptp:syntax-tree-raw-label (tptp-cst:label-tptp-file))
          tptp-file))
      (body))

    (rule eq-syntax-tree-label-line-comment
      (head
        (metta-equation
          (tptp:syntax-tree-label line-comment)
          (tptp-cst:label-line-comment)))
      (body))
    (rule eq-syntax-tree-raw-label-line-comment
      (head
        (metta-equation
          (tptp:syntax-tree-raw-label (tptp-cst:label-line-comment))
          line-comment))
      (body))

    (rule eq-syntax-tree-label-negation
      (head
        (metta-equation
          (tptp:syntax-tree-label negation)
          (tptp-cst:label-negation)))
      (body))
    (rule eq-syntax-tree-raw-label-negation
      (head
        (metta-equation
          (tptp:syntax-tree-raw-label (tptp-cst:label-negation))
          negation))
      (body))

    (rule eq-syntax-tree-label-paren
      (head
        (metta-equation
          (tptp:syntax-tree-label paren)
          (tptp-cst:label-paren)))
      (body))
    (rule eq-syntax-tree-raw-label-paren
      (head
        (metta-equation
          (tptp:syntax-tree-raw-label (tptp-cst:label-paren))
          paren))
      (body))

    (rule eq-syntax-tree-label-upper-word
      (head
        (metta-equation
          (tptp:syntax-tree-label upper-word)
          (tptp-cst:label-upper-word)))
      (body))
    (rule eq-syntax-tree-raw-label-upper-word
      (head
        (metta-equation
          (tptp:syntax-tree-raw-label (tptp-cst:label-upper-word))
          upper-word))
      (body))

    (rule eq-syntax-tree-label-variable-list
      (head
        (metta-equation
          (tptp:syntax-tree-label variable-list)
          (tptp-cst:label-variable-list)))
      (body))
    (rule eq-syntax-tree-raw-label-variable-list
      (head
        (metta-equation
          (tptp:syntax-tree-raw-label (tptp-cst:label-variable-list))
          variable-list))
      (body))

    (rule eq-raw-to-syntax-tree-node
      (head
        (metta-equation
          (tptp:raw->syntax-tree (node ?label ?payload))
          (tptp-cst:node
            (tptp:syntax-tree-label ?label)
            (tptp:raw->syntax-tree ?payload))))
      (body))
    (rule eq-raw-to-syntax-tree-codepoint
      (head
        (metta-equation
          (tptp:raw->syntax-tree (cp ?value))
          (tptp-cst:codepoint ?value)))
      (body))
    (rule eq-raw-to-syntax-tree-pair
      (head
        (metta-equation
          (tptp:raw->syntax-tree (pair ?left ?right))
          (tptp-cst:pair
            (tptp:raw->syntax-tree ?left)
            (tptp:raw->syntax-tree ?right))))
      (body))
    (rule eq-raw-to-syntax-tree-cons
      (head
        (metta-equation
          (tptp:raw->syntax-tree (cons ?first ?rest))
          (tptp-cst:cons
            (tptp:raw->syntax-tree ?first)
            (tptp:raw->syntax-tree ?rest))))
      (body))
    (rule eq-raw-to-syntax-tree-some
      (head
        (metta-equation
          (tptp:raw->syntax-tree (some ?value))
          (tptp-cst:some (tptp:raw->syntax-tree ?value))))
      (body))
    (rule eq-raw-to-syntax-tree-none
      (head
        (metta-equation
          (tptp:raw->syntax-tree none)
          (tptp-cst:none)))
      (body))
    (rule eq-raw-to-syntax-tree-nil
      (head
        (metta-equation
          (tptp:raw->syntax-tree nil)
          (tptp-cst:nil)))
      (body))

    (rule eq-syntax-tree-to-raw-node
      (head
        (metta-equation
          (tptp:syntax-tree->raw (tptp-cst:node ?label ?payload))
          (node
            (tptp:syntax-tree-raw-label ?label)
            (tptp:syntax-tree->raw ?payload))))
      (body))
    (rule eq-syntax-tree-to-raw-codepoint
      (head
        (metta-equation
          (tptp:syntax-tree->raw (tptp-cst:codepoint ?value))
          (cp ?value)))
      (body))
    (rule eq-syntax-tree-to-raw-pair
      (head
        (metta-equation
          (tptp:syntax-tree->raw (tptp-cst:pair ?left ?right))
          (pair
            (tptp:syntax-tree->raw ?left)
            (tptp:syntax-tree->raw ?right))))
      (body))
    (rule eq-syntax-tree-to-raw-cons
      (head
        (metta-equation
          (tptp:syntax-tree->raw (tptp-cst:cons ?first ?rest))
          (cons
            (tptp:syntax-tree->raw ?first)
            (tptp:syntax-tree->raw ?rest))))
      (body))
    (rule eq-syntax-tree-to-raw-some
      (head
        (metta-equation
          (tptp:syntax-tree->raw (tptp-cst:some ?value))
          (some (tptp:syntax-tree->raw ?value))))
      (body))
    (rule eq-syntax-tree-to-raw-none
      (head
        (metta-equation
          (tptp:syntax-tree->raw (tptp-cst:none))
          none))
      (body))
    (rule eq-syntax-tree-to-raw-nil
      (head
        (metta-equation
          (tptp:syntax-tree->raw (tptp-cst:nil))
          nil))
      (body))

    (rule eq-text-lower
      (head
        (metta-equation
          (tptp:text (node lower-word ?characters))
          (langdef:codepoints->string ?characters)))
      (body))
    (rule eq-text-upper
      (head
        (metta-equation
          (tptp:text (node upper-word ?characters))
          (langdef:codepoints->string ?characters)))
      (body))
    (rule eq-text-single-quoted
      (head
        (metta-equation
          (tptp:text (node single-quoted ?characters))
          (langdef:codepoints->string ?characters)))
      (body))
    (rule eq-text-back-quoted
      (head
        (metta-equation
          (tptp:text (node back-quoted ?characters))
          (langdef:codepoints->string ?characters)))
      (body))
    (rule eq-text-defined
      (head
        (metta-equation
          (tptp:text (node defined-word ?characters))
          (langdef:codepoints->string ?characters)))
      (body))
    (rule eq-text-system
      (head
        (metta-equation
          (tptp:text (node system-word ?characters))
          (langdef:codepoints->string ?characters)))
      (body))
    (rule eq-text-integer
      (head
        (metta-equation
          (tptp:text (node integer ?characters))
          (langdef:codepoints->string ?characters)))
      (body))
    (rule eq-text-rational
      (head
        (metta-equation
          (tptp:text (node rational ?characters))
          (langdef:codepoints->string ?characters)))
      (body))
    (rule eq-text-real
      (head
        (metta-equation
          (tptp:text (node real ?characters))
          (langdef:codepoints->string ?characters)))
      (body))
    (rule eq-text-distinct
      (head
        (metta-equation
          (tptp:text (node distinct-object ?characters))
          (langdef:codepoints->string ?characters)))
      (body))

    (rule eq-symbol-lower
      (head
        (metta-equation
          (tptp:symbol-name (node lower-word ?characters))
          (fo-cnf:symbol-name (metta-nullary fo-cnf:symbol-lower)
            (langdef:codepoints->string ?characters))))
      (body))
    (rule eq-symbol-single-quoted
      (head
        (metta-equation
          (tptp:symbol-name (node single-quoted ?characters))
          (fo-cnf:symbol-name (metta-nullary fo-cnf:symbol-quoted)
            (langdef:codepoints->string ?characters))))
      (body))
    (rule eq-symbol-back-quoted
      (head
        (metta-equation
          (tptp:symbol-name (node back-quoted ?characters))
          (fo-cnf:symbol-name (metta-nullary fo-cnf:symbol-quoted)
            (langdef:codepoints->string ?characters))))
      (body))
    (rule eq-symbol-defined
      (head
        (metta-equation
          (tptp:symbol-name (node defined-word ?characters))
          (fo-cnf:symbol-name (metta-nullary fo-cnf:symbol-defined)
            (langdef:codepoints->string ?characters))))
      (body))
    (rule eq-symbol-system
      (head
        (metta-equation
          (tptp:symbol-name (node system-word ?characters))
          (fo-cnf:symbol-name (metta-nullary fo-cnf:symbol-system)
            (langdef:codepoints->string ?characters))))
      (body))

    (rule eq-formula-name-lower
      (head
        (metta-equation
          (tptp:formula-name (node lower-word ?characters))
          (fo-cnf:formula-name-atomic
            (tptp:symbol-name (node lower-word ?characters)))))
      (body))
    (rule eq-formula-name-single-quoted
      (head
        (metta-equation
          (tptp:formula-name (node single-quoted ?characters))
          (fo-cnf:formula-name-atomic
            (tptp:symbol-name (node single-quoted ?characters)))))
      (body))
    (rule eq-formula-name-back-quoted
      (head
        (metta-equation
          (tptp:formula-name (node back-quoted ?characters))
          (fo-cnf:formula-name-atomic
            (tptp:symbol-name (node back-quoted ?characters)))))
      (body))
    (rule eq-formula-name-integer
      (head
        (metta-equation
          (tptp:formula-name (node integer ?characters))
          (fo-cnf:formula-name-integer
            (langdef:codepoints->string ?characters))))
      (body))

    (rule eq-role
      (head
        (metta-equation
          (tptp:role
            (node formula-role
              (pair (node lower-word ?characters) none)))
          (fo-cnf:role
            (langdef:codepoints->string ?characters)
            (metta-nullary fo-cnf:annotation-none))))
      (body))
    (rule eq-role-refined
      (head
        (metta-equation
          (tptp:role
            (node formula-role
              (pair (node lower-word ?characters) (some ?refinement))))
          (fo-cnf:role
            (langdef:codepoints->string ?characters)
            (fo-cnf:annotation-tree (tptp:syntax ?refinement)))))
      (body))

    (rule eq-annotation-none
      (head
        (metta-equation
          (tptp:annotation none)
          (metta-nullary fo-cnf:annotation-none)))
      (body))
    (rule eq-annotation-some
      (head
        (metta-equation
          (tptp:annotation (some ?annotation))
          (fo-cnf:annotation-tree (tptp:syntax ?annotation))))
      (body))

    (rule eq-syntax-list-1
      (head
        (metta-equation
          (tptp:syntax-list-1 ?first)
          (fo-cnf:syntax-list
            (fo-cnf:syntax-nodes-cons ?first
              (metta-nullary fo-cnf:syntax-nodes-nil)))))
      (body))
    (rule eq-syntax-list-2
      (head
        (metta-equation
          (tptp:syntax-list-2 ?first ?second)
          (fo-cnf:syntax-list
            (fo-cnf:syntax-nodes-cons ?first
              (fo-cnf:syntax-nodes-cons ?second
                (metta-nullary fo-cnf:syntax-nodes-nil))))))
      (body))
    (rule eq-syntax-list-3
      (head
        (metta-equation
          (tptp:syntax-list-3 ?first ?second ?third)
          (fo-cnf:syntax-list
            (fo-cnf:syntax-nodes-cons ?first
              (fo-cnf:syntax-nodes-cons ?second
                (fo-cnf:syntax-nodes-cons ?third
                  (metta-nullary fo-cnf:syntax-nodes-nil)))))))
      (body))
    (rule eq-syntax-label-and
      (head
        (metta-equation
          (tptp:syntax-label and)
          "and"))
      (body))
    (rule eq-syntax-label-application
      (head
        (metta-equation
          (tptp:syntax-label application)
          "application"))
      (body))
    (rule eq-syntax-label-arguments
      (head
        (metta-equation
          (tptp:syntax-label arguments)
          "arguments"))
      (body))
    (rule eq-syntax-label-atomic
      (head
        (metta-equation
          (tptp:syntax-label atomic)
          "atomic"))
      (body))
    (rule eq-syntax-label-back-quoted
      (head
        (metta-equation
          (tptp:syntax-label back-quoted)
          "back-quoted"))
      (body))
    (rule eq-syntax-label-block-comment
      (head
        (metta-equation
          (tptp:syntax-label block-comment)
          "block-comment"))
      (body))
    (rule eq-syntax-label-cnf
      (head
        (metta-equation
          (tptp:syntax-label cnf)
          "cnf"))
      (body))
    (rule eq-syntax-label-cnf-disjunction
      (head
        (metta-equation
          (tptp:syntax-label cnf-disjunction)
          "cnf-disjunction"))
      (body))
    (rule eq-syntax-label-constant
      (head
        (metta-equation
          (tptp:syntax-label constant)
          "constant"))
      (body))
    (rule eq-syntax-label-defined-application
      (head
        (metta-equation
          (tptp:syntax-label defined-application)
          "defined-application"))
      (body))
    (rule eq-syntax-label-defined-constant
      (head
        (metta-equation
          (tptp:syntax-label defined-constant)
          "defined-constant"))
      (body))
    (rule eq-syntax-label-defined-word
      (head
        (metta-equation
          (tptp:syntax-label defined-word)
          "defined-word"))
      (body))
    (rule eq-syntax-label-disequality
      (head
        (metta-equation
          (tptp:syntax-label disequality)
          "disequality"))
      (body))
    (rule eq-syntax-label-distinct
      (head
        (metta-equation
          (tptp:syntax-label distinct)
          "distinct"))
      (body))
    (rule eq-syntax-label-distinct-object
      (head
        (metta-equation
          (tptp:syntax-label distinct-object)
          "distinct-object"))
      (body))
    (rule eq-syntax-label-equality
      (head
        (metta-equation
          (tptp:syntax-label equality)
          "equality"))
      (body))
    (rule eq-syntax-label-exists
      (head
        (metta-equation
          (tptp:syntax-label exists)
          "exists"))
      (body))
    (rule eq-syntax-label-fof
      (head
        (metta-equation
          (tptp:syntax-label fof)
          "fof"))
      (body))
    (rule eq-syntax-label-forall
      (head
        (metta-equation
          (tptp:syntax-label forall)
          "forall"))
      (body))
    (rule eq-syntax-label-formula-role
      (head
        (metta-equation
          (tptp:syntax-label formula-role)
          "formula-role"))
      (body))
    (rule eq-syntax-label-general-atomic
      (head
        (metta-equation
          (tptp:syntax-label general-atomic)
          "general-atomic"))
      (body))
    (rule eq-syntax-label-general-distinct
      (head
        (metta-equation
          (tptp:syntax-label general-distinct)
          "general-distinct"))
      (body))
    (rule eq-syntax-label-general-empty-list
      (head
        (metta-equation
          (tptp:syntax-label general-empty-list)
          "general-empty-list"))
      (body))
    (rule eq-syntax-label-general-function
      (head
        (metta-equation
          (tptp:syntax-label general-function)
          "general-function"))
      (body))
    (rule eq-syntax-label-general-list
      (head
        (metta-equation
          (tptp:syntax-label general-list)
          "general-list"))
      (body))
    (rule eq-syntax-label-general-number
      (head
        (metta-equation
          (tptp:syntax-label general-number)
          "general-number"))
      (body))
    (rule eq-syntax-label-general-term
      (head
        (metta-equation
          (tptp:syntax-label general-term)
          "general-term"))
      (body))
    (rule eq-syntax-label-general-terms
      (head
        (metta-equation
          (tptp:syntax-label general-terms)
          "general-terms"))
      (body))
    (rule eq-syntax-label-general-variable
      (head
        (metta-equation
          (tptp:syntax-label general-variable)
          "general-variable"))
      (body))
    (rule eq-syntax-label-iff
      (head
        (metta-equation
          (tptp:syntax-label iff)
          "iff"))
      (body))
    (rule eq-syntax-label-implies
      (head
        (metta-equation
          (tptp:syntax-label implies)
          "implies"))
      (body))
    (rule eq-syntax-label-include
      (head
        (metta-equation
          (tptp:syntax-label include)
          "include"))
      (body))
    (rule eq-syntax-label-integer
      (head
        (metta-equation
          (tptp:syntax-label integer)
          "integer"))
      (body))
    (rule eq-syntax-label-line-comment
      (head
        (metta-equation
          (tptp:syntax-label line-comment)
          "line-comment"))
      (body))
    (rule eq-syntax-label-lower-word
      (head
        (metta-equation
          (tptp:syntax-label lower-word)
          "lower-word"))
      (body))
    (rule eq-syntax-label-name-list
      (head
        (metta-equation
          (tptp:syntax-label name-list)
          "name-list"))
      (body))
    (rule eq-syntax-label-nand
      (head
        (metta-equation
          (tptp:syntax-label nand)
          "nand"))
      (body))
    (rule eq-syntax-label-negation
      (head
        (metta-equation
          (tptp:syntax-label negation)
          "negation"))
      (body))
    (rule eq-syntax-label-negative-literal
      (head
        (metta-equation
          (tptp:syntax-label negative-literal)
          "negative-literal"))
      (body))
    (rule eq-syntax-label-negative-paren-literal
      (head
        (metta-equation
          (tptp:syntax-label negative-paren-literal)
          "negative-paren-literal"))
      (body))
    (rule eq-syntax-label-nor
      (head
        (metta-equation
          (tptp:syntax-label nor)
          "nor"))
      (body))
    (rule eq-syntax-label-number
      (head
        (metta-equation
          (tptp:syntax-label number)
          "number"))
      (body))
    (rule eq-syntax-label-or
      (head
        (metta-equation
          (tptp:syntax-label or)
          "or"))
      (body))
    (rule eq-syntax-label-paren
      (head
        (metta-equation
          (tptp:syntax-label paren)
          "paren"))
      (body))
    (rule eq-syntax-label-positive-literal
      (head
        (metta-equation
          (tptp:syntax-label positive-literal)
          "positive-literal"))
      (body))
    (rule eq-syntax-label-rational
      (head
        (metta-equation
          (tptp:syntax-label rational)
          "rational"))
      (body))
    (rule eq-syntax-label-real
      (head
        (metta-equation
          (tptp:syntax-label real)
          "real"))
      (body))
    (rule eq-syntax-label-reverse-implies
      (head
        (metta-equation
          (tptp:syntax-label reverse-implies)
          "reverse-implies"))
      (body))
    (rule eq-syntax-label-single-quoted
      (head
        (metta-equation
          (tptp:syntax-label single-quoted)
          "single-quoted"))
      (body))
    (rule eq-syntax-label-system-application
      (head
        (metta-equation
          (tptp:syntax-label system-application)
          "system-application"))
      (body))
    (rule eq-syntax-label-system-constant
      (head
        (metta-equation
          (tptp:syntax-label system-constant)
          "system-constant"))
      (body))
    (rule eq-syntax-label-system-word
      (head
        (metta-equation
          (tptp:syntax-label system-word)
          "system-word"))
      (body))
    (rule eq-syntax-label-tptp-file
      (head
        (metta-equation
          (tptp:syntax-label tptp-file)
          "tptp-file"))
      (body))
    (rule eq-syntax-label-upper-word
      (head
        (metta-equation
          (tptp:syntax-label upper-word)
          "upper-word"))
      (body))
    (rule eq-syntax-label-variable
      (head
        (metta-equation
          (tptp:syntax-label variable)
          "variable"))
      (body))
    (rule eq-syntax-label-variable-list
      (head
        (metta-equation
          (tptp:syntax-label variable-list)
          "variable-list"))
      (body))
    (rule eq-syntax-label-xor
      (head
        (metta-equation
          (tptp:syntax-label xor)
          "xor"))
      (body))
    (rule eq-syntax-node
      (head
        (metta-equation
          (tptp:syntax (node ?label ?payload))
          (let ?label-text (tptp:syntax-label ?label)
            (tptp:syntax-list-3
              (fo-cnf:syntax-atom "node")
              (fo-cnf:syntax-atom ?label-text)
              (tptp:syntax ?payload)))))
      (body))
    (rule eq-syntax-pair
      (head
        (metta-equation
          (tptp:syntax (pair ?first ?second))
          (tptp:syntax-list-3
            (fo-cnf:syntax-atom "pair")
            (tptp:syntax ?first)
            (tptp:syntax ?second))))
      (body))
    (rule eq-syntax-cons
      (head
        (metta-equation
          (tptp:syntax (cons ?first ?rest))
          (tptp:syntax-list-3
            (fo-cnf:syntax-atom "cons")
            (tptp:syntax ?first)
            (tptp:syntax ?rest))))
      (body))
    (rule eq-syntax-some
      (head
        (metta-equation
          (tptp:syntax (some ?value))
          (tptp:syntax-list-2
            (fo-cnf:syntax-atom "some")
            (tptp:syntax ?value))))
      (body))
    (rule eq-syntax-none
      (head
        (metta-equation
          (tptp:syntax none)
          (tptp:syntax-list-1 (fo-cnf:syntax-atom "none"))))
      (body))
    (rule eq-syntax-nil
      (head
        (metta-equation
          (tptp:syntax nil)
          (tptp:syntax-list-1 (fo-cnf:syntax-atom "nil"))))
      (body))
    (rule eq-syntax-codepoint
      (head
        (metta-equation
          (tptp:syntax (cp ?value))
          (tptp:syntax-list-2
            (fo-cnf:syntax-atom "cp")
            (fo-cnf:syntax-integer ?value))))
      (body))

    (rule eq-numeric-kind-integer
      (head
        (metta-equation
          (tptp:numeric-kind (node integer ?characters))
          (metta-nullary fo-cnf:number-integer)))
      (body))
    (rule eq-numeric-kind-rational
      (head
        (metta-equation
          (tptp:numeric-kind (node rational ?characters))
          (metta-nullary fo-cnf:number-rational)))
      (body))
    (rule eq-numeric-kind-real
      (head
        (metta-equation
          (tptp:numeric-kind (node real ?characters))
          (metta-nullary fo-cnf:number-real)))
      (body))

    (rule eq-term-variable
      (head
        (metta-equation
          (tptp:term (node variable (node upper-word ?characters)) ?scope)
          (fo-cnf:term-variable
            (fo-cnf:variable-id ?scope
              (fo-cnf:variable-name
                (langdef:codepoints->string ?characters))))))
      (body))
    (rule eq-term-constant
      (head
        (metta-equation
          (tptp:term (node constant ?word) ?scope)
          (fo-cnf:term-function
            (tptp:symbol-name ?word)
            (metta-nullary fo-cnf:terms-nil))))
      (body))
    (rule eq-term-defined-constant
      (head
        (metta-equation
          (tptp:term (node defined-constant ?word) ?scope)
          (fo-cnf:term-function
            (tptp:symbol-name ?word)
            (metta-nullary fo-cnf:terms-nil))))
      (body))
    (rule eq-term-system-constant
      (head
        (metta-equation
          (tptp:term (node system-constant ?word) ?scope)
          (fo-cnf:term-function
            (tptp:symbol-name ?word)
            (metta-nullary fo-cnf:terms-nil))))
      (body))
    (rule eq-term-application
      (head
        (metta-equation
          (tptp:term
            (node application
              (pair ?word (node arguments ?arguments))) ?scope)
          (fo-cnf:term-function
            (tptp:symbol-name ?word)
            (tptp:arguments ?arguments ?scope))))
      (body))
    (rule eq-term-defined-application
      (head
        (metta-equation
          (tptp:term
            (node defined-application
              (pair ?word (node arguments ?arguments))) ?scope)
          (fo-cnf:term-function
            (tptp:symbol-name ?word)
            (tptp:arguments ?arguments ?scope))))
      (body))
    (rule eq-term-system-application
      (head
        (metta-equation
          (tptp:term
            (node system-application
              (pair ?word (node arguments ?arguments))) ?scope)
          (fo-cnf:term-function
            (tptp:symbol-name ?word)
            (tptp:arguments ?arguments ?scope))))
      (body))
    (rule eq-term-number
      (head
        (metta-equation
          (tptp:term (node number ?number) ?scope)
          (fo-cnf:term-number
            (tptp:numeric-kind ?number) (tptp:text ?number))))
      (body))
    (rule eq-term-distinct
      (head
        (metta-equation
          (tptp:term (node distinct ?object) ?scope)
          (fo-cnf:term-distinct (tptp:text ?object))))
      (body))

    (rule eq-arguments
      (head
        (metta-equation
          (tptp:arguments (pair ?first ?rest) ?scope)
          (fo-cnf:terms-cons
            (tptp:term ?first ?scope)
            (tptp:term-rest ?rest ?scope))))
      (body))
    (rule eq-term-rest-cons
      (head
        (metta-equation
          (tptp:term-rest (cons ?first ?rest) ?scope)
          (fo-cnf:terms-cons
            (tptp:term ?first ?scope)
            (tptp:term-rest ?rest ?scope))))
      (body))
    (rule eq-term-rest-nil
      (head
        (metta-equation
          (tptp:term-rest nil ?scope)
          (metta-nullary fo-cnf:terms-nil)))
      (body))

    (rule eq-predicate-constant
      (head
        (metta-equation
          (tptp:predicate (node constant ?word) ?scope)
          (fo-cnf:atom-predicate
            (tptp:symbol-name ?word)
            (metta-nullary fo-cnf:terms-nil))))
      (body))
    (rule eq-predicate-application
      (head
        (metta-equation
          (tptp:predicate
            (node application
              (pair ?word (node arguments ?arguments))) ?scope)
          (fo-cnf:atom-predicate
            (tptp:symbol-name ?word)
            (tptp:arguments ?arguments ?scope))))
      (body))
    (rule eq-predicate-defined-constant
      (head
        (metta-equation
          (tptp:predicate (node defined-constant ?word) ?scope)
          (fo-cnf:atom-predicate
            (tptp:symbol-name ?word)
            (metta-nullary fo-cnf:terms-nil))))
      (body))
    (rule eq-predicate-defined-application
      (head
        (metta-equation
          (tptp:predicate
            (node defined-application
              (pair ?word (node arguments ?arguments))) ?scope)
          (fo-cnf:atom-predicate
            (tptp:symbol-name ?word)
            (tptp:arguments ?arguments ?scope))))
      (body))
    (rule eq-predicate-system-constant
      (head
        (metta-equation
          (tptp:predicate (node system-constant ?word) ?scope)
          (fo-cnf:atom-predicate
            (tptp:symbol-name ?word)
            (metta-nullary fo-cnf:terms-nil))))
      (body))
    (rule eq-predicate-system-application
      (head
        (metta-equation
          (tptp:predicate
            (node system-application
              (pair ?word (node arguments ?arguments))) ?scope)
          (fo-cnf:atom-predicate
            (tptp:symbol-name ?word)
            (tptp:arguments ?arguments ?scope))))
      (body))

    (rule eq-literal-positive
      (head
        (metta-equation
          (tptp:literal
            (node positive-literal (node atomic ?predicate)) ?scope)
          (fo-cnf:literal-positive
            (tptp:predicate ?predicate ?scope))))
      (body))
    (rule eq-literal-negative
      (head
        (metta-equation
          (tptp:literal
            (node negative-literal (node atomic ?predicate)) ?scope)
          (fo-cnf:literal-negative
            (tptp:predicate ?predicate ?scope))))
      (body))
    (rule eq-literal-negative-parenthesized
      (head
        (metta-equation
          (tptp:literal
            (node negative-paren-literal (node atomic ?predicate)) ?scope)
          (fo-cnf:literal-negative
            (tptp:predicate ?predicate ?scope))))
      (body))
    (rule eq-literal-disequality
      (head
        (metta-equation
          (tptp:literal
            (node disequality (pair ?left ?right)) ?scope)
          (fo-cnf:literal-negative
            (fo-cnf:atom-equality
              (tptp:term ?left ?scope)
              (tptp:term ?right ?scope)))))
      (body))
    (rule eq-literal-equality
      (head
        (metta-equation
          (tptp:literal
            (node equality (pair ?left ?right)) ?scope)
          (fo-cnf:literal-positive
            (fo-cnf:atom-equality
              (tptp:term ?left ?scope)
              (tptp:term ?right ?scope)))))
      (body))

    (rule eq-clause
      (head
        (metta-equation
          (tptp:clause
            (node cnf-disjunction (pair ?first ?rest)) ?scope)
          (fo-cnf:literals-cons
            (tptp:literal ?first ?scope)
            (tptp:literal-rest ?rest ?scope))))
      (body))
    (rule eq-literal-rest-cons
      (head
        (metta-equation
          (tptp:literal-rest (cons ?first ?rest) ?scope)
          (fo-cnf:literals-cons
            (tptp:literal ?first ?scope)
            (tptp:literal-rest ?rest ?scope))))
      (body))
    (rule eq-literal-rest-nil
      (head
        (metta-equation
          (tptp:literal-rest nil ?scope)
          (metta-nullary fo-cnf:literals-nil)))
      (body))

    (rule eq-cnf
      (head
        (metta-equation
          (tptp:cnf
            (node cnf
              (pair ?name
                (pair ?role (pair ?formula ?annotation))))
            ?source ?index)
          (let ?scope (fo-cnf:occurrence ?source ?index)
            (fo-cnf:clause
              ?scope
              (tptp:formula-name ?name)
              (tptp:role ?role)
              (tptp:clause ?formula ?scope)
              (tptp:annotation ?annotation)
              (metta-nullary fo-cnf:source-span-unknown)))))
      (body))
    (rule eq-inputs-cons
      (head
        (metta-equation
          (tptp:inputs (cons ?input ?rest) ?source ?index)
          (fo-cnf:clauses-cons
            (tptp:cnf ?input ?source ?index)
            (tptp:inputs ?rest ?source (+ ?index 1)))))
      (body))
    (rule eq-inputs-nil
      (head
        (metta-equation
          (tptp:inputs nil ?source ?index)
          (metta-nullary fo-cnf:clauses-nil)))
      (body))
    (rule eq-ast-to-problem
      (head
        (metta-equation
          (tptp:ast->problem (node tptp-file ?inputs) ?digest)
          (let ?source (fo-cnf:source-digest ?digest)
            (fo-cnf:problem ?source
              (tptp:inputs ?inputs ?source 0)))))
      (body))
    (rule eq-parse-to-clause-data
      (head
        (metta-equation
          (tptp:parse->clause-data
            (LangDef:ImportPrepared TptpFofCnfV1 ?pack ?digest ?values))
          (let ?syntax-tree
              (tptp:parse->syntax-tree
                (LangDef:ImportPrepared TptpFofCnfV1 ?pack ?digest ?values))
            (tptp:syntax-tree->problem ?syntax-tree ?digest))))
      (body))
    (rule eq-parse-to-syntax-tree
      (head
        (metta-equation
          (tptp:parse->syntax-tree
            (LangDef:ImportPrepared TptpFofCnfV1 ?pack ?digest
              (metta-nullary ?ast)))
          (tptp:raw->syntax-tree ?ast)))
      (body))
    (rule eq-prepared-raw
      (head
        (metta-equation
          (tptp:prepared-raw
            (LangDef:ImportPrepared TptpFofCnfV1 ?pack ?digest
              (metta-nullary ?ast)))
          ?ast))
      (body))
    (rule eq-prepared-digest
      (head
        (metta-equation
          (tptp:prepared-digest
            (LangDef:ImportPrepared TptpFofCnfV1 ?pack ?digest ?values))
          ?digest))
      (body))
    (rule eq-syntax-tree-to-problem
      (head
        (metta-equation
          (tptp:syntax-tree->problem ?syntax-tree ?digest)
          (tptp:ast->problem
            (tptp:syntax-tree->raw ?syntax-tree) ?digest)))
      (body))
    (rule eq-parse-to-import
      (head
        (metta-equation
          (tptp-cnf:parse->import
            (LangDef:ImportPrepared TptpFofCnfV1 ?pack ?digest ?values))
          (let ?syntax-tree
              (tptp:parse->syntax-tree
                (LangDef:ImportPrepared TptpFofCnfV1 ?pack ?digest ?values))
            (let ?problem
                (tptp:syntax-tree->problem ?syntax-tree ?digest)
              (let ?empty (tptp:empty empty)
                (LangDef:ImportReady ?syntax-tree
                  (cons-atom ?problem ?empty)))))))
      (body))))
