!(collapse
   (gslt:DirectGroundDifferentV1
     (DirectGroundDifferentV1 DirectLeftV1 DirectRightV1)))
!(collapse
   (gslt:DirectGroundDifferentV1
     (DirectGroundDifferentV1 DirectSameV1 DirectSameV1)))
!(collapse
   (gslt:DirectGroundDifferentTwiceV1
     (DirectGroundDifferentTwiceV1
       DirectFirstV1 DirectSecondV1 DirectThirdV1)))
!(collapse
   (gslt:DirectGroundDifferentTwiceV1
     (DirectGroundDifferentTwiceV1
       DirectFirstV1 DirectSecondV1 DirectFirstV1)))
