#!/usr/bin/env python3
"""Generate the isolated PeTTa typecheck-v2 census catalog header."""

from __future__ import annotations

import argparse
from dataclasses import dataclass
import json
from pathlib import Path
import re
from typing import Sequence


WITNESS_SCHEMA = "cetta-petta-typecheck-v2-census-witnesses-v2"
DESCRIPTOR_FIELDS = ("scope", "kind", "mapping", "axis")
SEMANTIC_AXES = frozenset({
    "shape-compatibility",
    "result-cardinality-grading",
    "source-evaluated-stage-evidence",
    "open-world-unknown-approximation",
})
_C_IDENTIFIER = re.compile(r"[A-Z][A-Z0-9_]*\Z")


class GenerationError(ValueError):
    pass


@dataclass(frozen=True)
class CensusEvent:
    tag: str
    name: str
    scope: str
    kind: str
    mapping: str
    axis: str


def c_string(value: str) -> str:
    return json.dumps(value, ensure_ascii=True)


def event_tag(name: str) -> str:
    tag = name.upper().replace("-", "_")
    if not _C_IDENTIFIER.fullmatch(tag):
        raise GenerationError(f"{name}: cannot form a C event tag")
    return tag


def catalog_from_payload(payload: object) -> tuple[CensusEvent, ...]:
    if not isinstance(payload, dict):
        raise GenerationError("census witness ledger is not an object")
    if payload.get("schema") != WITNESS_SCHEMA:
        raise GenerationError("census witness ledger has an unsupported schema")
    raw_witnesses = payload.get("witnesses")
    if not isinstance(raw_witnesses, dict) or not raw_witnesses:
        raise GenerationError("census witness ledger has no witnesses")

    events: list[CensusEvent] = []
    tags: set[str] = set()
    for name in sorted(raw_witnesses):
        raw = raw_witnesses[name]
        if not isinstance(name, str) or not name:
            raise GenerationError("census witness has no event name")
        if not isinstance(raw, dict):
            raise GenerationError(f"{name}: census witness is not an object")
        values: dict[str, str] = {}
        for field in DESCRIPTOR_FIELDS:
            value = raw.get(field)
            if not isinstance(value, str) or not value:
                raise GenerationError(f"{name}: census witness has no {field}")
            values[field] = value
        if values["scope"] not in {"oracle", "mechanism"}:
            raise GenerationError(f"{name}: invalid census scope {values['scope']}")
        if values["kind"] not in {"rule", "mechanism"}:
            raise GenerationError(f"{name}: invalid census mapping kind {values['kind']}")
        if values["axis"] not in SEMANTIC_AXES:
            raise GenerationError(f"{name}: unknown semantic axis {values['axis']}")
        tag = event_tag(name)
        if tag in tags:
            raise GenerationError(f"{name}: duplicate C event tag {tag}")
        tags.add(tag)
        events.append(CensusEvent(tag, name, **values))
    return tuple(events)


def render_header(events: Sequence[CensusEvent]) -> str:
    if not events:
        raise GenerationError("cannot render an empty census catalog")
    lines = [
        "#ifndef CETTA_PETTA_TYPECHECK_CENSUS_H",
        "#define CETTA_PETTA_TYPECHECK_CENSUS_H",
        "",
        "/* Generated by tools/generate_petta_typecheck_v2_census_v1.py. */",
        "",
        "#ifndef CETTA_BUILD_WITH_PETTA_TYPECHECK_CENSUS",
        "#define CETTA_BUILD_WITH_PETTA_TYPECHECK_CENSUS 0",
        "#endif",
        "",
        "#define CETTA_PETTA_TYPECHECK_CENSUS_EVENTS(X) \\",
    ]
    for index, event in enumerate(events):
        suffix = " \\" if index + 1 < len(events) else ""
        lines.append(
            f"    X({event.tag}, {c_string(event.name)}, "
            f"{c_string(event.scope)}, {c_string(event.kind)}, "
            f"{c_string(event.mapping)}, {c_string(event.axis)}){suffix}"
        )
    lines.extend([
        "",
        "#if CETTA_BUILD_WITH_PETTA_TYPECHECK_CENSUS",
        "",
        "typedef enum {",
        "#define CETTA_PETTA_TYPECHECK_CENSUS_ENUM(                          \\",
        "    tag, name, scope, kind, mapping, axis)                          \\",
        "    CETTA_PETTA_TYPECHECK_CENSUS_EVENT_##tag,",
        "    CETTA_PETTA_TYPECHECK_CENSUS_EVENTS(",
        "        CETTA_PETTA_TYPECHECK_CENSUS_ENUM)",
        "#undef CETTA_PETTA_TYPECHECK_CENSUS_ENUM",
        "    CETTA_PETTA_TYPECHECK_CENSUS_EVENT_COUNT,",
        "} CettaPettaTypecheckCensusEvent;",
        "",
        "void cetta_petta_typecheck_census_hit_at(",
        "    CettaPettaTypecheckCensusEvent event, const char *origin);",
        "",
        "#define CETTA_PETTA_TYPECHECK_CENSUS_HIT(event)                     \\",
        "    cetta_petta_typecheck_census_hit_at(event, __func__)",
        "",
        "#define CETTA_PETTA_TYPECHECK_CENSUS_HIT_IF(condition, event)        \\",
        "    do {                                                               \\",
        "        if (condition)                                                \\",
        "            CETTA_PETTA_TYPECHECK_CENSUS_HIT(event);                 \\",
        "    } while (0)",
        "",
        "#else",
        "",
        "#define CETTA_PETTA_TYPECHECK_CENSUS_HIT(event) ((void)0)",
        "#define CETTA_PETTA_TYPECHECK_CENSUS_HIT_IF(condition, event) ((void)0)",
        "",
        "#endif",
        "",
        "#endif /* CETTA_PETTA_TYPECHECK_CENSUS_H */",
        "",
    ])
    return "\n".join(lines)


def main(argv: Sequence[str] | None = None) -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument("--witness-ledger", required=True, type=Path)
    parser.add_argument("--output", required=True, type=Path)
    parser.add_argument("--check", action="store_true")
    args = parser.parse_args(argv)
    try:
        payload = json.loads(args.witness_ledger.read_text(encoding="utf-8"))
        rendered = render_header(catalog_from_payload(payload))
        if args.check:
            existing = args.output.read_text(encoding="utf-8")
            if existing != rendered:
                raise GenerationError(
                    "generated census catalog differs from the checked-in header"
                )
        else:
            args.output.parent.mkdir(parents=True, exist_ok=True)
            args.output.write_text(rendered, encoding="utf-8")
    except (OSError, json.JSONDecodeError, GenerationError) as error:
        parser.exit(1, f"census catalog generation rejected: {error}\n")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
