#ifndef CETTA_GDL_FINITE_HERBRAND_H
#define CETTA_GDL_FINITE_HERBRAND_H

#include "gdl_source_presentation.h"

#include <stdbool.h>
#include <stddef.h>

/* The finite typed ground-term carrier generated by one authored GDL type
 * profile.  This is language semantics used by native calculi; it is not an
 * authority, a checker verdict, or a parser execution mode. */
typedef struct CettaGdlFiniteHerbrandV1 CettaGdlFiniteHerbrandV1;

typedef struct {
    size_t max_terms;
    size_t max_constructor_applications;
    size_t max_rounds;
    size_t max_depth;
} CettaGdlFiniteHerbrandLimitsV1;

typedef enum {
    CETTA_GDL_FINITE_HERBRAND_ESTABLISHED_V1 = 1,
    CETTA_GDL_FINITE_HERBRAND_OUTSIDE_FRAGMENT_V1,
    CETTA_GDL_FINITE_HERBRAND_INCOMPLETE_V1,
    CETTA_GDL_FINITE_HERBRAND_ENGINE_FAULT_V1,
} CettaGdlFiniteHerbrandKindV1;

typedef struct {
    CettaGdlFiniteHerbrandKindV1 kind;
    /* Established carries the completed carrier.  Incomplete retains the
     * exact partial carrier/frontier reached within the supplied bounds;
     * neither permits a negative membership conclusion. */
    CettaGdlFiniteHerbrandV1 *domain;
} CettaGdlFiniteHerbrandResultV1;

typedef struct {
    Atom *term;
    const char *exact_type;
    size_t depth;
    size_t construction_count;
} CettaGdlFiniteHerbrandTermViewV1;

typedef struct {
    size_t signature_index;
    size_t statement_ordinal;
    size_t name_ordinal;
    const size_t *argument_term_indices;
    size_t argument_count;
} CettaGdlFiniteHerbrandConstructionViewV1;

typedef struct {
    size_t signature_index;
    size_t statement_ordinal;
    size_t name_ordinal;
    const char *name;
    const char *const *argument_types;
    size_t argument_count;
} CettaGdlFiniteHerbrandRelationViewV1;

typedef struct {
    size_t types;
    size_t signatures;
    size_t constructors;
    size_t relations;
    size_t subtype_edges;
    size_t terms;
    size_t construction_witnesses;
    size_t constructor_applications;
    size_t rounds;
    size_t maximum_depth;
} CettaGdlFiniteHerbrandStatsV1;

/* Construct the least finite typed ground-term carrier.  Support identity is
 * (structural term, exact result type); every distinct signature/argument
 * construction of that support member is retained as a witness.  Productive
 * recursion that crosses a supplied bound is Incomplete, never a finite
 * completion claim. */
CettaGdlFiniteHerbrandResultV1 cetta_gdl_finite_herbrand_construct_v1(
    const GdlSourceProfileV1 *profile,
    CettaGdlFiniteHerbrandLimitsV1 limits);

void cetta_gdl_finite_herbrand_destroy_v1(
    CettaGdlFiniteHerbrandV1 *domain);

size_t cetta_gdl_finite_herbrand_term_count_v1(
    const CettaGdlFiniteHerbrandV1 *domain);

size_t cetta_gdl_finite_herbrand_relation_count_v1(
    const CettaGdlFiniteHerbrandV1 *domain);

bool cetta_gdl_finite_herbrand_term_view_v1(
    const CettaGdlFiniteHerbrandV1 *domain,
    size_t index,
    CettaGdlFiniteHerbrandTermViewV1 *view_out);

bool cetta_gdl_finite_herbrand_construction_view_v1(
    const CettaGdlFiniteHerbrandV1 *domain,
    size_t term_index,
    size_t construction_index,
    CettaGdlFiniteHerbrandConstructionViewV1 *view_out);

bool cetta_gdl_finite_herbrand_relation_view_v1(
    const CettaGdlFiniteHerbrandV1 *domain,
    size_t relation_index,
    CettaGdlFiniteHerbrandRelationViewV1 *view_out);

bool cetta_gdl_finite_herbrand_find_term_v1(
    const CettaGdlFiniteHerbrandV1 *domain,
    Atom *term,
    const char *exact_type,
    size_t *index_out);

/* Enumerate every exact typed support member whose structural term equals
 * `term` and whose exact type is accepted at `expected_type`.  The return
 * value is the total match count even when `capacity` is smaller, so callers
 * can size a proof-relevant assignment fibre without scanning the carrier. */
size_t cetta_gdl_finite_herbrand_matching_terms_v1(
    const CettaGdlFiniteHerbrandV1 *domain,
    Atom *term,
    const char *expected_type,
    size_t *indices_out,
    size_t capacity);

bool cetta_gdl_finite_herbrand_type_accepts_v1(
    const CettaGdlFiniteHerbrandV1 *domain,
    const char *actual_type,
    const char *expected_type);

bool cetta_gdl_finite_herbrand_stats_v1(
    const CettaGdlFiniteHerbrandV1 *domain,
    CettaGdlFiniteHerbrandStatsV1 *stats_out);

#endif /* CETTA_GDL_FINITE_HERBRAND_H */
