#ifndef CETTA_PETTA_TYPECHECK_CENSUS_H
#define CETTA_PETTA_TYPECHECK_CENSUS_H

/* Generated by tools/generate_petta_typecheck_v2_census_v1.py. */

#ifndef CETTA_BUILD_WITH_PETTA_TYPECHECK_CENSUS
#define CETTA_BUILD_WITH_PETTA_TYPECHECK_CENSUS 0
#endif

#define CETTA_PETTA_TYPECHECK_CENSUS_EVENTS(X) \
    X(ACTUAL_ALIAS_EXPAND, "actual-alias-expand", "oracle", "rule", "consistent-alias-left", "shape-compatibility") \
    X(ACTUAL_UNION_ALL, "actual-union-all", "oracle", "rule", "consistent-union-left", "shape-compatibility") \
    X(ACTUAL_UNION_ALL_ACCEPT, "actual-union-all-accept", "oracle", "rule", "consistent-union-left", "shape-compatibility") \
    X(ACTUAL_UNION_MEMBER_REJECT, "actual-union-member-reject", "oracle", "mechanism", "actual-union-universal-rejection", "shape-compatibility") \
    X(ADMINISTRATIVE_ALIAS_NONDET_PRESERVED, "administrative-alias-nondet-preserved", "oracle", "mechanism", "administrative-alias-nondeterminism-preservation", "result-cardinality-grading") \
    X(ARROW_COMPATIBLE, "arrow-compatible", "oracle", "rule", "consistent-arrow", "shape-compatibility") \
    X(ARROW_COMPONENT_REJECT, "arrow-component-reject", "oracle", "mechanism", "arrow-component-incompatibility", "shape-compatibility") \
    X(ARROW_MODE_DET_EXACT, "arrow-mode-det-exact", "oracle", "rule", "mode-fits-det-det", "result-cardinality-grading") \
    X(ARROW_MODE_DET_TO_SEMIDET, "arrow-mode-det-to-semidet", "oracle", "rule", "mode-fits-det-semidet", "result-cardinality-grading") \
    X(ARROW_MODE_EFFECT_ACCEPT, "arrow-mode-effect-accept", "oracle", "rule", "mode-fits-effect", "result-cardinality-grading") \
    X(ARROW_MODE_NONDET_ACCEPT, "arrow-mode-nondet-accept", "oracle", "rule", "mode-fits-nondet", "result-cardinality-grading") \
    X(ARROW_MODE_PLAIN_ACCEPT, "arrow-mode-plain-accept", "oracle", "rule", "mode-fits-plain", "result-cardinality-grading") \
    X(ARROW_MODE_REJECT, "arrow-mode-reject", "oracle", "mechanism", "arrow-mode-incompatibility", "result-cardinality-grading") \
    X(ARROW_MODE_SEMIDET_EXACT, "arrow-mode-semidet-exact", "oracle", "rule", "mode-fits-semidet-semidet", "result-cardinality-grading") \
    X(ARROW_SHAPE_REJECT, "arrow-shape-reject", "oracle", "mechanism", "arrow-shape-incompatibility", "shape-compatibility") \
    X(ASCRIPTION_ACTUAL_UNION_ACCEPT, "ascription-actual-union-accept", "oracle", "rule", "overlap-union-left", "shape-compatibility") \
    X(ASCRIPTION_ACTUAL_UNION_REJECT, "ascription-actual-union-reject", "oracle", "mechanism", "overlap-union-left-exhausted", "shape-compatibility") \
    X(ASCRIPTION_ALIAS_LEFT, "ascription-alias-left", "oracle", "rule", "overlap-alias-left", "shape-compatibility") \
    X(ASCRIPTION_ALIAS_RIGHT, "ascription-alias-right", "oracle", "rule", "overlap-alias-right", "shape-compatibility") \
    X(ASCRIPTION_FORWARD_ACCEPT, "ascription-forward-accept", "oracle", "rule", "overlap-forward", "shape-compatibility") \
    X(ASCRIPTION_NO_OVERLAP, "ascription-no-overlap", "oracle", "mechanism", "explicit-ascription-disjointness", "shape-compatibility") \
    X(ASCRIPTION_REQUIRED_UNION_ACCEPT, "ascription-required-union-accept", "oracle", "rule", "overlap-union-right", "shape-compatibility") \
    X(ASCRIPTION_REQUIRED_UNION_REJECT, "ascription-required-union-reject", "oracle", "mechanism", "overlap-union-right-exhausted", "shape-compatibility") \
    X(ASCRIPTION_REVERSE_ACCEPT, "ascription-reverse-accept", "oracle", "rule", "overlap-reverse", "shape-compatibility") \
    X(CLAUSE_SLOT_ALIAS_PRESERVED, "clause-slot-alias-preserved", "mechanism", "mechanism", "caller-visible-substitution-preservation", "source-evaluated-stage-evidence") \
    X(COLLAPSE_ELEMENT_CONFLICT, "collapse-element-conflict", "oracle", "mechanism", "collapse-proved-element-conflict", "shape-compatibility") \
    X(COLLAPSE_RESULT_LIST_SHAPE, "collapse-result-list-shape", "oracle", "rule", "expression-result-type-collapse", "shape-compatibility") \
    X(COLLAPSE_UNKNOWN_ELEMENT, "collapse-unknown-element", "oracle", "mechanism", "collapse-retains-list-shape-with-unknown-element", "open-world-unknown-approximation") \
    X(COMMITTED_EFFECT_UNKNOWN_REJECT, "committed-effect-unknown-reject", "oracle", "mechanism", "committed-effect-requires-positive-evidence", "result-cardinality-grading") \
    X(CONDITIONAL_NO_RESULT_BRANCH, "conditional-no-result-branch", "oracle", "mechanism", "conditional-no-result-branch", "result-cardinality-grading") \
    X(CONTEXTUAL_DIRECT_CUT_COMMIT_ACCEPT, "contextual-direct-cut-commit-accept", "oracle", "mechanism", "committed-direct-cut-overlap", "result-cardinality-grading") \
    X(CONTEXTUAL_LAMBDA_COMMITMENT_ACCEPT, "contextual-lambda-commitment-accept", "oracle", "mechanism", "committed-lambda-determinism-preservation", "result-cardinality-grading") \
    X(CONTEXTUAL_LAMBDA_COMMITMENT_REJECT, "contextual-lambda-commitment-reject", "oracle", "mechanism", "committed-lambda-nondeterminism-rejection", "result-cardinality-grading") \
    X(CONTEXTUAL_LET_CUT_COMMIT_ACCEPT, "contextual-let-cut-commit-accept", "oracle", "mechanism", "committed-let-cut-overlap", "result-cardinality-grading") \
    X(EVAL_DYNAMIC_EFFECT_UNKNOWN, "eval-dynamic-effect-unknown", "oracle", "mechanism", "evaluation-withholds-cardinality-evidence", "source-evaluated-stage-evidence") \
    X(EXPRESSION_EFFECT_COLLAPSE, "expression-effect-collapse", "oracle", "rule", "expression-effect-collapse", "result-cardinality-grading") \
    X(EXPRESSION_EFFECT_FOLDALL, "expression-effect-foldall", "oracle", "rule", "expression-effect-foldall", "result-cardinality-grading") \
    X(EXPRESSION_EFFECT_ONCE_DET, "expression-effect-once-det", "oracle", "rule", "expression-effect-once-det", "result-cardinality-grading") \
    X(EXPRESSION_EFFECT_ONCE_NONDET, "expression-effect-once-nondet", "oracle", "rule", "expression-effect-once-nondet", "result-cardinality-grading") \
    X(EXPRESSION_EFFECT_ONCE_SEMIDET, "expression-effect-once-semidet", "oracle", "rule", "expression-effect-once-semidet", "result-cardinality-grading") \
    X(EXPRESSION_EFFECT_SUPERPOSE_NONDET, "expression-effect-superpose-nondet", "oracle", "mechanism", "superpose-operator-preserves-nondeterministic-grade", "result-cardinality-grading") \
    X(FOLDALL_EMPTY_RETURNS_INITIALIZER, "foldall-empty-returns-initializer", "oracle", "rule", "expression-result-type-foldall-empty", "shape-compatibility") \
    X(FOLDALL_GENERATOR_ELEMENT_UNKNOWN, "foldall-generator-element-unknown", "oracle", "mechanism", "foldall-unproven-generator-element", "open-world-unknown-approximation") \
    X(INFERENCE_ALL_BOTTOM_CASE_UNPUBLISHED, "inference-all-bottom-case-unpublished", "oracle", "mechanism", "inferred-all-bottom-withholds-output-evidence", "open-world-unknown-approximation") \
    X(INFERENCE_ALL_BOTTOM_UNPUBLISHED, "inference-all-bottom-unpublished", "oracle", "mechanism", "inferred-all-bottom-withholds-output-evidence", "open-world-unknown-approximation") \
    X(INFERENCE_BOTTOM_BRANCH_UNPUBLISHED, "inference-bottom-branch-unpublished", "oracle", "mechanism", "inferred-bottom-branch-withholds-output-evidence", "open-world-unknown-approximation") \
    X(INFERENCE_EMPTY_ALTERNATIVE_SET_UNPUBLISHED, "inference-empty-alternative-set-unpublished", "oracle", "mechanism", "inferred-empty-alternative-set-withholds-output-evidence", "open-world-unknown-approximation") \
    X(INFERENCE_INFERRED_VALUE_CANDIDATE_IGNORED, "inference-inferred-value-candidate-ignored", "oracle", "mechanism", "inferred-function-is-not-explicit-value-evidence", "open-world-unknown-approximation") \
    X(INFERENCE_OUTPUT_SHAPE_WIDENS_UNKNOWN, "inference-output-shape-widens-unknown", "oracle", "mechanism", "inferred-output-publication-normalization", "open-world-unknown-approximation") \
    X(INFERENCE_PARAMETER_TAINT, "inference-parameter-taint", "oracle", "mechanism", "inferred-parameter-conflict-widens-unknown", "open-world-unknown-approximation") \
    X(INFERENCE_VALUE_CANDIDATE_AMBIGUOUS, "inference-value-candidate-ambiguous", "oracle", "mechanism", "inferred-value-candidate-ambiguity-widens-unknown", "open-world-unknown-approximation") \
    X(INFERENCE_VALUE_CANDIDATE_SINGLETON, "inference-value-candidate-singleton", "oracle", "mechanism", "inferred-value-candidate-singleton", "shape-compatibility") \
    X(NEWTYPE_ACTUAL_REQUIRED_UNION, "newtype-actual-required-union", "oracle", "rule", "consistent-union-right", "shape-compatibility") \
    X(NEWTYPE_ACTUAL_UNION_REQUIRED, "newtype-actual-union-required", "oracle", "rule", "consistent-union-left", "shape-compatibility") \
    X(NEWTYPE_ACTUAL_WILDCARD_ACCEPT, "newtype-actual-wildcard-accept", "oracle", "rule", "consistent-dyn-right", "open-world-unknown-approximation") \
    X(NEWTYPE_DISTINCT_REJECT, "newtype-distinct-reject", "oracle", "mechanism", "newtype-nominal-distinctness", "shape-compatibility") \
    X(NEWTYPE_IDENTITY_ACCEPT, "newtype-identity-accept", "oracle", "rule", "consistent-refl", "shape-compatibility") \
    X(NEWTYPE_LITERAL_BRAND_REJECT, "newtype-literal-brand-reject", "oracle", "mechanism", "literal-newtype-introduction-withheld", "shape-compatibility") \
    X(NEWTYPE_REPRESENTATION_ACCEPT, "newtype-representation-accept", "oracle", "rule", "consistent-newtype-representation", "shape-compatibility") \
    X(NEWTYPE_REPRESENTATION_REJECT, "newtype-representation-reject", "oracle", "mechanism", "newtype-representation-incompatibility", "shape-compatibility") \
    X(NEWTYPE_REQUIRED_REJECT, "newtype-required-reject", "oracle", "mechanism", "newtype-introduction-requires-brand", "shape-compatibility") \
    X(NEWTYPE_WILDCARD_REPRESENTATION_REJECT, "newtype-wildcard-representation-reject", "oracle", "mechanism", "newtype-wildcard-representation-non-vacuity", "open-world-unknown-approximation") \
    X(PATTERN_CANDIDATE_AMBIGUOUS, "pattern-candidate-ambiguous", "oracle", "mechanism", "pattern-candidate-multiplicity-preservation", "shape-compatibility") \
    X(PATTERN_CANDIDATE_OPEN_SPECIALIZE, "pattern-candidate-open-specialize", "oracle", "mechanism", "pattern-candidate-singleton-open-specialization", "shape-compatibility") \
    X(PATTERN_CANDIDATE_VARIANT_REPEAT, "pattern-candidate-variant-repeat", "oracle", "mechanism", "pattern-candidate-variant-deduplication", "shape-compatibility") \
    X(QUOTED_INNER_DATA_FORM_HELD, "quoted-inner-data-form-held", "oracle", "mechanism", "quotation-keeps-inner-data-form-as-data", "source-evaluated-stage-evidence") \
    X(QUOTED_INNER_TYPE_FORM_HELD, "quoted-inner-type-form-held", "oracle", "mechanism", "quotation-keeps-inner-type-form-as-data", "source-evaluated-stage-evidence") \
    X(RATIONAL_STRUCTURAL_CYCLE_ACCEPT, "rational-structural-cycle-accept", "oracle", "mechanism", "rational-tree-structural-compatibility", "shape-compatibility") \
    X(RATIONAL_STRUCTURAL_CYCLE_REJECT, "rational-structural-cycle-reject", "oracle", "mechanism", "rational-tree-structural-conflict", "shape-compatibility") \
    X(REQUIRED_ALIAS_EXPAND, "required-alias-expand", "oracle", "rule", "consistent-alias-right", "shape-compatibility") \
    X(REQUIRED_UNION_ANY, "required-union-any", "oracle", "rule", "consistent-union-right", "shape-compatibility") \
    X(REQUIRED_UNION_MEMBER_ACCEPT, "required-union-member-accept", "oracle", "rule", "consistent-union-right", "shape-compatibility") \
    X(REQUIRED_UNION_NONE_ACCEPT, "required-union-none-accept", "oracle", "mechanism", "required-union-existential-rejection", "shape-compatibility") \
    X(SELECTION_CASE_LIST_TOTAL, "selection-case-list-total", "oracle", "mechanism", "selection-case-proper-list-evidence", "source-evaluated-stage-evidence") \
    X(SELECTION_CONDITIONAL_LIST_TOTAL, "selection-conditional-list-total", "oracle", "mechanism", "selection-conditional-proper-list-evidence", "source-evaluated-stage-evidence") \
    X(SELECTION_IDENTITY_BINDING_BOOL_TOTAL, "selection-identity-binding-bool-total", "oracle", "mechanism", "selection-identity-binding-bound-bool-evidence", "source-evaluated-stage-evidence") \
    X(SELECTION_IDENTITY_BINDING_LIST_TOTAL, "selection-identity-binding-list-total", "oracle", "mechanism", "selection-identity-binding-proper-list-evidence", "source-evaluated-stage-evidence") \
    X(SELECTION_PATTERN_NOT_TOTAL, "selection-pattern-not-total", "oracle", "mechanism", "selection-partial-pattern-withholds-deterministic-grade", "result-cardinality-grading") \
    X(SELECTION_SOURCE_LIST_SHAPE_ONLY, "selection-source-list-shape-only", "oracle", "mechanism", "selection-data-expression-publishes-only-list-shape", "source-evaluated-stage-evidence") \
    X(SELECTION_SOURCE_OPAQUE, "selection-source-opaque", "oracle", "mechanism", "selection-evaluated-source-has-no-shape-evidence", "source-evaluated-stage-evidence") \
    X(STRUCTURAL_ARITY_REJECT, "structural-arity-reject", "oracle", "mechanism", "structural-arity-incompatibility", "shape-compatibility") \
    X(STRUCTURAL_ATOM_EXACT, "structural-atom-exact", "oracle", "mechanism", "structural-atom-identity", "shape-compatibility") \
    X(STRUCTURAL_ATOM_REJECT, "structural-atom-reject", "oracle", "mechanism", "structural-atom-incompatibility", "shape-compatibility") \
    X(STRUCTURAL_COMPATIBLE, "structural-compatible", "oracle", "mechanism", "structural-recursive-compatibility", "shape-compatibility") \
    X(STRUCTURAL_COMPONENT_REJECT, "structural-component-reject", "oracle", "mechanism", "structural-component-incompatibility", "shape-compatibility") \
    X(STRUCTURAL_KIND_REJECT, "structural-kind-reject", "oracle", "mechanism", "structural-kind-incompatibility", "shape-compatibility") \
    X(TYPE_VAR_ACTUAL_BIND_ACCEPT, "type-var-actual-bind-accept", "oracle", "mechanism", "type-variable-substitution", "shape-compatibility") \
    X(TYPE_VAR_ACTUAL_BIND_REJECT, "type-var-actual-bind-reject", "oracle", "mechanism", "acyclic-bind-deferred-to-rational-replay", "shape-compatibility") \
    X(TYPE_VAR_ACTUAL_UNION_SELF, "type-var-actual-union-self", "oracle", "mechanism", "type-variable-union-self-membership", "shape-compatibility") \
    X(TYPE_VAR_IDENTITY, "type-var-identity", "oracle", "mechanism", "type-variable-identity", "shape-compatibility") \
    X(TYPE_VAR_REQUIRED_BIND_ACCEPT, "type-var-required-bind-accept", "oracle", "mechanism", "type-variable-substitution", "shape-compatibility") \
    X(TYPE_VAR_REQUIRED_BIND_REJECT, "type-var-required-bind-reject", "oracle", "mechanism", "acyclic-bind-deferred-to-rational-replay", "shape-compatibility") \
    X(TYPE_VAR_REQUIRED_UNION_SELF, "type-var-required-union-self", "oracle", "mechanism", "type-variable-union-self-membership", "shape-compatibility") \
    X(WILDCARD_ACTUAL_ACCEPT, "wildcard-actual-accept", "oracle", "mechanism", "dynamic-actual-compatibility", "open-world-unknown-approximation") \
    X(WILDCARD_REQUIRED_ACCEPT, "wildcard-required-accept", "oracle", "mechanism", "dynamic-required-compatibility", "open-world-unknown-approximation")

#if CETTA_BUILD_WITH_PETTA_TYPECHECK_CENSUS

typedef enum {
#define CETTA_PETTA_TYPECHECK_CENSUS_ENUM(                          \
    tag, name, scope, kind, mapping, axis)                          \
    CETTA_PETTA_TYPECHECK_CENSUS_EVENT_##tag,
    CETTA_PETTA_TYPECHECK_CENSUS_EVENTS(
        CETTA_PETTA_TYPECHECK_CENSUS_ENUM)
#undef CETTA_PETTA_TYPECHECK_CENSUS_ENUM
    CETTA_PETTA_TYPECHECK_CENSUS_EVENT_COUNT,
} CettaPettaTypecheckCensusEvent;

void cetta_petta_typecheck_census_hit_at(
    CettaPettaTypecheckCensusEvent event, const char *origin);

#define CETTA_PETTA_TYPECHECK_CENSUS_HIT(event)                     \
    cetta_petta_typecheck_census_hit_at(event, __func__)

#define CETTA_PETTA_TYPECHECK_CENSUS_HIT_IF(condition, event)        \
    do {                                                               \
        if (condition)                                                \
            CETTA_PETTA_TYPECHECK_CENSUS_HIT(event);                 \
    } while (0)

#else

#define CETTA_PETTA_TYPECHECK_CENSUS_HIT(event) ((void)0)
#define CETTA_PETTA_TYPECHECK_CENSUS_HIT_IF(condition, event) ((void)0)

#endif

#endif /* CETTA_PETTA_TYPECHECK_CENSUS_H */
