#ifndef CETTA_STATS_H
#define CETTA_STATS_H

#include "atom.h"
#include <stdio.h>
#include <stdint.h>

typedef struct Space Space;

typedef enum {
    CETTA_RUNTIME_COUNTER_BINDINGS_LOOKUP = 0,
    CETTA_RUNTIME_COUNTER_BINDINGS_CLONE = 1,
    CETTA_RUNTIME_COUNTER_BINDINGS_ADD = 2,
    CETTA_RUNTIME_COUNTER_BINDINGS_CONSTRAINT_ADD = 3,
    CETTA_RUNTIME_COUNTER_BINDINGS_MERGE = 4,
    CETTA_RUNTIME_COUNTER_RENAME_VARS = 5,
    CETTA_RUNTIME_COUNTER_QUERY_EQUATIONS = 6,
    CETTA_RUNTIME_COUNTER_QUERY_EQUATION_CANDIDATES = 7,
    CETTA_RUNTIME_COUNTER_QUERY_EQUATION_LEGACY_CANDIDATES = 8,
    CETTA_RUNTIME_COUNTER_QUERY_EQUATION_SUBST_CANDIDATES = 9,
    CETTA_RUNTIME_COUNTER_EQ_INDEX_REBUILD = 10,
    CETTA_RUNTIME_COUNTER_TY_INDEX_REBUILD = 11,
    CETTA_RUNTIME_COUNTER_HASHCONS_ATTEMPT = 12,
    CETTA_RUNTIME_COUNTER_HASHCONS_HIT = 13,
    CETTA_RUNTIME_COUNTER_HASHCONS_INSERT = 14,
    CETTA_RUNTIME_COUNTER_HASH_SPACE_EXACT_LOOKUP = 15,
    CETTA_RUNTIME_COUNTER_HASH_SPACE_EXACT_HIT = 16,
    CETTA_RUNTIME_COUNTER_SUBST_QUERY_EXACT_SHORTCUT = 17,
    CETTA_RUNTIME_COUNTER_IMPORTED_BRIDGE_V2_HIT = 18,
    CETTA_RUNTIME_COUNTER_IMPORTED_BRIDGE_V2_FALLBACK = 19,
    CETTA_RUNTIME_COUNTER_IMPORTED_BRIDGE_V3_HIT = 20,
    CETTA_RUNTIME_COUNTER_IMPORTED_BRIDGE_V3_FALLBACK = 21,
    CETTA_RUNTIME_COUNTER_SPACE_PUSH = 22,
    CETTA_RUNTIME_COUNTER_SPACE_POP = 23,
    CETTA_RUNTIME_COUNTER_QUEUE_COMPACT = 24,
    CETTA_RUNTIME_COUNTER_REGISTRY_RESOLVE_HIT = 25,
    CETTA_RUNTIME_COUNTER_REGISTRY_RESOLVE_REWRITE = 26,
    CETTA_RUNTIME_COUNTER_REGISTRY_RESOLVE_NOOP = 27,
    CETTA_RUNTIME_COUNTER_QUERY_EQUATION_SUBST_EMITTED = 28,
    CETTA_RUNTIME_COUNTER_QUERY_EQUATION_SUBST_CANDIDATE_FALLBACK = 29,
    CETTA_RUNTIME_COUNTER_QUERY_EQUATION_SUBST_BUCKET_FALLBACK = 30,
    CETTA_RUNTIME_COUNTER_BINDINGS_APPLY = 31,
    CETTA_RUNTIME_COUNTER_BINDINGS_FREE = 32,
    CETTA_RUNTIME_COUNTER_BINDINGS_FREE_NONEMPTY = 33,
    CETTA_RUNTIME_COUNTER_BINDINGS_RELEASED_ENTRY_CAPACITY = 34,
    CETTA_RUNTIME_COUNTER_BINDINGS_RELEASED_CONSTRAINT_CAPACITY = 35,
    CETTA_RUNTIME_COUNTER_BINDINGS_NORMALIZE = 36,
    CETTA_RUNTIME_COUNTER_ATTACHED_ACT_OPEN = 37,
    CETTA_RUNTIME_COUNTER_ATTACHED_ACT_QUERY = 38,
    CETTA_RUNTIME_COUNTER_ATTACHED_ACT_MATERIALIZE = 39,
    CETTA_RUNTIME_COUNTER_ATTACHED_ACT_MATERIALIZE_ATOMS = 40,
    CETTA_RUNTIME_COUNTER_BODY_VISIBLE_CACHE_LOOKUP = 41,
    CETTA_RUNTIME_COUNTER_BODY_VISIBLE_CACHE_HIT = 42,
    CETTA_RUNTIME_COUNTER_BODY_VISIBLE_CACHE_STORE = 43,
    CETTA_RUNTIME_COUNTER_TABLE_HIT = 44,
    CETTA_RUNTIME_COUNTER_TABLE_MISS = 45,
    CETTA_RUNTIME_COUNTER_TABLE_STALE_MISS = 46,
    CETTA_RUNTIME_COUNTER_TABLE_REUSE = 47,
    CETTA_RUNTIME_COUNTER_TABLE_ANSWER_STAGED = 48,
    CETTA_RUNTIME_COUNTER_ANSWER_REF_EMIT = 49,
    CETTA_RUNTIME_COUNTER_ANSWER_REF_INFLATE_CALL = 50,
    CETTA_RUNTIME_COUNTER_ANSWER_REF_MATERIALIZE_CALL = 51,
    CETTA_RUNTIME_COUNTER_ANSWER_REF_MATERIALIZE_BYTES = 52,
    CETTA_RUNTIME_COUNTER_SPACE_REVISION_BUMP = 53,
    CETTA_RUNTIME_COUNTER_TERM_UNIVERSE_LOOKUP = 54,
    CETTA_RUNTIME_COUNTER_TERM_UNIVERSE_HIT = 55,
    CETTA_RUNTIME_COUNTER_TERM_UNIVERSE_INSERT = 56,
    CETTA_RUNTIME_COUNTER_TERM_UNIVERSE_BYTE_ENTRY = 57,
    CETTA_RUNTIME_COUNTER_TERM_UNIVERSE_FALLBACK_ENTRY = 58,
    CETTA_RUNTIME_COUNTER_TERM_UNIVERSE_BLOB_BYTES = 59,
    CETTA_RUNTIME_COUNTER_TERM_UNIVERSE_LAZY_DECODE = 60,
    CETTA_RUNTIME_COUNTER_OUTCOME_VARIANT_FACTOR_ATTEMPT = 61,
    CETTA_RUNTIME_COUNTER_OUTCOME_VARIANT_FACTOR_SUCCESS = 62,
    CETTA_RUNTIME_COUNTER_OUTCOME_VARIANT_SLOT_MATERIALIZE = 63,
    CETTA_RUNTIME_COUNTER_MORK_ADD_CALL = 64,
    CETTA_RUNTIME_COUNTER_MORK_ADD_LOWER_NS = 65,
    CETTA_RUNTIME_COUNTER_MORK_ADD_FFI_NS = 66,
    CETTA_RUNTIME_COUNTER_MORK_ADD_EXPR_BYTES = 67,
    CETTA_RUNTIME_COUNTER_MORK_ADD_BATCH_CALL = 68,
    CETTA_RUNTIME_COUNTER_MORK_ADD_BATCH_ITEMS = 69,
    CETTA_RUNTIME_COUNTER_MORK_ADD_BATCH_PACK_NS = 70,
    CETTA_RUNTIME_COUNTER_MORK_ADD_BATCH_FFI_NS = 71,
    CETTA_RUNTIME_COUNTER_MORK_ADD_BATCH_PACKET_BYTES = 72,
    CETTA_RUNTIME_COUNTER_MORK_ADD_BATCH_NATIVE_NS = 73,
    CETTA_RUNTIME_COUNTER_MORK_ADD_BATCH_DISPATCH_NS = 74,
    CETTA_RUNTIME_COUNTER_MORK_ADD_BATCH_RESOLVE_NS = 75,
    CETTA_RUNTIME_COUNTER_MORK_ADD_STREAM_EVAL_NS = 76,
    CETTA_RUNTIME_COUNTER_MORK_ADD_STREAM_INSERT_NS = 77,
    CETTA_RUNTIME_COUNTER_OUTCOME_VARIANT_SLOT_SINK = 78,
    CETTA_RUNTIME_COUNTER_OUTCOME_VARIANT_PREFIX_COMPACT = 79,
    CETTA_RUNTIME_COUNTER_OUTCOME_VARIANT_MATERIALIZE_TOP_LEVEL = 80,
    CETTA_RUNTIME_COUNTER_OUTCOME_VARIANT_MATERIALIZE_INTERPRET_TUPLE = 81,
    CETTA_RUNTIME_COUNTER_OUTCOME_VARIANT_MATERIALIZE_DISPATCH_HEAD = 82,
    CETTA_RUNTIME_COUNTER_OUTCOME_VARIANT_MATERIALIZE_DISPATCH_CALL_TERM = 83,
    CETTA_RUNTIME_COUNTER_OUTCOME_VARIANT_MATERIALIZE_LET_CHAIN = 84,
    CETTA_RUNTIME_COUNTER_OUTCOME_VARIANT_MATERIALIZE_ERROR_FILTER = 85,
    CETTA_RUNTIME_COUNTER_BINDINGS_LOOKUP_CACHE_HIT = 86,
    CETTA_RUNTIME_COUNTER_BINDINGS_LOOKUP_CACHE_MISS = 87,
    CETTA_RUNTIME_COUNTER_BINDINGS_APPLY_SPACE_CONJ_DEFAULT = 88,
    CETTA_RUNTIME_COUNTER_BINDINGS_APPLY_SPACE_CONJ_IMPORTED = 89,
    CETTA_RUNTIME_COUNTER_BINDINGS_APPLY_EVAL_CHAIN_STEP = 90,
    CETTA_RUNTIME_COUNTER_BINDINGS_APPLY_EVAL_CHAIN_LAST = 91,
    CETTA_RUNTIME_COUNTER_BINDINGS_APPLY_EVAL_CHAIN_BODY = 92,
    CETTA_RUNTIME_COUNTER_BINDINGS_APPLY_MATCH_TEMPLATE = 93,
    CETTA_RUNTIME_COUNTER_BINDINGS_LOOKUP_RESOLVE = 94,
    CETTA_RUNTIME_COUNTER_BINDINGS_LOOKUP_ADD_GUARD = 95,
    CETTA_RUNTIME_COUNTER_BINDINGS_LOOKUP_APPLY = 96,
    CETTA_RUNTIME_COUNTER_BINDINGS_LOOKUP_LOOP_CHECK = 97,
    CETTA_RUNTIME_COUNTER_BINDINGS_LOOKUP_MATCH = 98,
    CETTA_RUNTIME_COUNTER_BINDINGS_LOOP_CALL_PARSE = 99,
    CETTA_RUNTIME_COUNTER_BINDINGS_LOOP_CALL_UNIFY = 100,
    CETTA_RUNTIME_COUNTER_BINDINGS_LOOP_CALL_NATIVE_QUERY = 101,
    CETTA_RUNTIME_COUNTER_BINDINGS_LOOP_CALL_MORK_DIRECT_ROW = 102,
    CETTA_RUNTIME_COUNTER_BINDINGS_LOOP_CALL_MORK_CONJ_MERGE = 103,
    CETTA_RUNTIME_COUNTER_BINDINGS_LOOP_CALL_MORK_CONJ_DIRECT = 104,
    CETTA_RUNTIME_COUNTER_BINDINGS_LOOP_CALL_IMPORTED_EXACT = 105,
    CETTA_RUNTIME_COUNTER_BINDINGS_LOOP_CALL_IMPORTED_LEGACY = 106,
    CETTA_RUNTIME_COUNTER_BINDINGS_LOOP_CALL_NATIVE_CANDIDATE = 107,
    CETTA_RUNTIME_COUNTER_BINDINGS_LOOP_CALL_EQ_STORE = 108,
    CETTA_RUNTIME_COUNTER_BINDINGS_LOOP_CALL_EQ_DECODED = 109,
    CETTA_RUNTIME_COUNTER_BINDINGS_APPLY_REWRITE_NODE_VISIT = 110,
    CETTA_RUNTIME_COUNTER_BINDINGS_APPLY_EPOCH_NODE_VISIT = 111,
    CETTA_RUNTIME_COUNTER_BINDINGS_LOOP_NODE_VISIT = 112,
    CETTA_RUNTIME_COUNTER_QUERY_VISIBLE_NODE_VISIT = 113,
    CETTA_RUNTIME_COUNTER_QUERY_VISIBLE_DEDUP_SCAN = 114,
    CETTA_RUNTIME_COUNTER_BINDINGS_SEEN_SCAN = 115,
    CETTA_RUNTIME_COUNTER_EVAL_C_STACK_GUARD_BUDGET_BYTES = 116,
    CETTA_RUNTIME_COUNTER_EVAL_C_STACK_GUARD_DEPTH_PEAK = 117,
    CETTA_RUNTIME_COUNTER_EVAL_C_STACK_GUARD_DELTA_BYTES_PEAK = 118,
    CETTA_RUNTIME_COUNTER_EVAL_C_STACK_GUARD_TRIP_EVAL = 119,
    CETTA_RUNTIME_COUNTER_EVAL_C_STACK_GUARD_TRIP_BIND = 120,
    CETTA_RUNTIME_COUNTER_EVAL_C_STACK_GUARD_TRIP_BIND_TYPED = 121,
    CETTA_RUNTIME_COUNTER_PERSISTENT_ARENA_ALLOC_BYTES = 122,
    CETTA_RUNTIME_COUNTER_PERSISTENT_ARENA_LIVE_BYTES_PEAK = 123,
    CETTA_RUNTIME_COUNTER_PERSISTENT_ARENA_RESERVED_BYTES_PEAK = 124,
    CETTA_RUNTIME_COUNTER_EVAL_ARENA_ALLOC_BYTES = 125,
    CETTA_RUNTIME_COUNTER_EVAL_ARENA_LIVE_BYTES_PEAK = 126,
    CETTA_RUNTIME_COUNTER_EVAL_ARENA_RESERVED_BYTES_PEAK = 127,
    CETTA_RUNTIME_COUNTER_SCRATCH_ARENA_ALLOC_BYTES = 128,
    CETTA_RUNTIME_COUNTER_SCRATCH_ARENA_LIVE_BYTES_PEAK = 129,
    CETTA_RUNTIME_COUNTER_SCRATCH_ARENA_RESERVED_BYTES_PEAK = 130,
    CETTA_RUNTIME_COUNTER_BINDINGS_ENTRY_POOL_BYTES = 131,
    CETTA_RUNTIME_COUNTER_BINDINGS_ENTRY_POOL_BYTES_PEAK = 132,
    CETTA_RUNTIME_COUNTER_BINDINGS_ENTRY_RETAINED_BYTES = 133,
    CETTA_RUNTIME_COUNTER_BINDINGS_ENTRY_RETAINED_BYTES_PEAK = 134,
    CETTA_RUNTIME_COUNTER_BINDINGS_ENTRY_ACTIVE_BYTES_PEAK = 135,
    CETTA_RUNTIME_COUNTER_BINDINGS_CONSTRAINT_POOL_BYTES = 136,
    CETTA_RUNTIME_COUNTER_BINDINGS_CONSTRAINT_POOL_BYTES_PEAK = 137,
    CETTA_RUNTIME_COUNTER_BINDINGS_CONSTRAINT_RETAINED_BYTES = 138,
    CETTA_RUNTIME_COUNTER_BINDINGS_CONSTRAINT_RETAINED_BYTES_PEAK = 139,
    CETTA_RUNTIME_COUNTER_BINDINGS_CONSTRAINT_ACTIVE_BYTES_PEAK = 140,
    CETTA_RUNTIME_COUNTER_EVAL_TAIL_SAFE_POINT_COUNT = 141,
    CETTA_RUNTIME_COUNTER_EVAL_TAIL_RECLAIMED_BYTES = 142,
    CETTA_RUNTIME_COUNTER_EVAL_TAIL_PROMOTED_BINDING_ENTRIES_PEAK = 143,
    CETTA_RUNTIME_COUNTER_EVAL_TAIL_PROMOTED_BINDING_CONSTRAINTS_PEAK = 144,
    CETTA_RUNTIME_COUNTER_QUERY_EPISODE_SURVIVOR_ARENA_ALLOC_BYTES = 145,
    CETTA_RUNTIME_COUNTER_QUERY_EPISODE_SURVIVOR_ARENA_LIVE_BYTES_PEAK = 146,
    CETTA_RUNTIME_COUNTER_QUERY_EPISODE_SURVIVOR_ARENA_RESERVED_BYTES_PEAK = 147,
    CETTA_RUNTIME_COUNTER_QUERY_EPISODE_PROMOTED_ANSWER_COUNT = 148,
    CETTA_RUNTIME_COUNTER_QUERY_EPISODE_PROMOTED_ANSWER_BYTES = 149,
    CETTA_RUNTIME_COUNTER_QUERY_EPISODE_DELAYED_OUTCOME_SURVIVOR_COUNT = 150,
    CETTA_RUNTIME_COUNTER_COUNT = 151
} CettaRuntimeCounter;

typedef struct {
    uint64_t counters[CETTA_RUNTIME_COUNTER_COUNT];
} CettaRuntimeStats;

#ifndef CETTA_BUILD_WITH_RUNTIME_STATS
#define CETTA_BUILD_WITH_RUNTIME_STATS 0
#endif

#ifndef CETTA_BUILD_WITH_RUNTIME_TIMING
#define CETTA_BUILD_WITH_RUNTIME_TIMING 0
#endif

const char *cetta_runtime_counter_name(CettaRuntimeCounter counter);
void cetta_runtime_stats_reset(void);
void cetta_runtime_stats_enable(void);
void cetta_runtime_stats_disable(void);
bool cetta_runtime_stats_is_enabled(void);
void cetta_runtime_stats_add(CettaRuntimeCounter counter, uint64_t delta);
void cetta_runtime_stats_set(CettaRuntimeCounter counter, uint64_t value);
void cetta_runtime_stats_update_max(CettaRuntimeCounter counter, uint64_t value);
void cetta_runtime_stats_snapshot(CettaRuntimeStats *out);
void cetta_runtime_stats_print(FILE *out, const CettaRuntimeStats *stats);
void cetta_runtime_stats_populate_space(Space *space, Arena *a,
                                        const CettaRuntimeStats *stats);

#if !CETTA_BUILD_WITH_RUNTIME_STATS && !defined(CETTA_RUNTIME_STATS_IMPL)
#define cetta_runtime_stats_is_enabled() false
#define cetta_runtime_stats_add(counter, delta)                                  \
    do {                                                                         \
    } while (0)
#define cetta_runtime_stats_set(counter, value)                                  \
    do {                                                                         \
    } while (0)
#define cetta_runtime_stats_update_max(counter, value)                           \
    do {                                                                         \
    } while (0)
#define cetta_runtime_stats_inc(counter)                                         \
    do {                                                                         \
    } while (0)
#else
static inline void cetta_runtime_stats_inc(CettaRuntimeCounter counter) {
    cetta_runtime_stats_add(counter, 1);
}
#endif

static inline bool cetta_runtime_timing_is_enabled(void) {
#if CETTA_BUILD_WITH_RUNTIME_STATS && CETTA_BUILD_WITH_RUNTIME_TIMING
    return cetta_runtime_stats_is_enabled();
#else
    return false;
#endif
}

#endif
